NEOTERM_PKG_HOMEPAGE=https://sourceforge.net/projects/gpg-crypter/
NEOTERM_PKG_DESCRIPTION="A graphical front-end to GnuPG(GPG) using the GTK3 toolkit and libgpgme"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.4.1
NEOTERM_PKG_REVISION=24
NEOTERM_PKG_SRCURL=https://downloads.sourceforge.net/gpg-crypter/gpg-crypter-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=1f7e2b27bf4a27ecbb07bce9cd40d1c08477a3bd065ba7d1a75d1732e4bdc023
NEOTERM_PKG_DEPENDS="glib, gpgme, gtk3, pinentry-gtk"
NEOTERM_PKG_RM_AFTER_INSTALL="lib/locale"
