NEOTERM_PKG_HOMEPAGE=https://www.ladspa.org/
NEOTERM_PKG_DESCRIPTION="Linux Audio Developer's Simple Plugin API"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.17
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://www.ladspa.org/download/ladspa_sdk_${NEOTERM_PKG_VERSION}.tgz
NEOTERM_PKG_SHA256=27d24f279e4b81bd17ecbdcc38e4c42991bb388826c0b200067ce0eb59d3da5b
NEOTERM_PKG_DEPENDS="libc++, libsndfile"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="targets"

neoterm_step_pre_configure() {
	NEOTERM_PKG_SRCDIR+="/src"
	NEOTERM_PKG_BUILDDIR="$NEOTERM_PKG_SRCDIR"
}
