NEOTERM_PKG_HOMEPAGE=https://www.lysator.liu.se/~nisse/nettle/
NEOTERM_PKG_DESCRIPTION="Cryptographic library that is designed to fit easily in more or less any context"
NEOTERM_PKG_LICENSE="GPL-2.0, LGPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=3.9.1
NEOTERM_PKG_SRCURL=https://mirrors.kernel.org/gnu/nettle/nettle-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=ccfeff981b0ca71bbd6fbcb054f407c60ffb644389a5be80d6716d5b550c6ce3
NEOTERM_PKG_DEPENDS="libgmp"
NEOTERM_PKG_BREAKS="libnettle-dev"
NEOTERM_PKG_REPLACES="libnettle-dev"
