NEOTERM_PKG_HOMEPAGE=https://www.kde.org/
NEOTERM_PKG_DESCRIPTION="Large set of desktop Qt widgets (KDE)"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="Simeon Huang <symeon@librehat.com>"
NEOTERM_PKG_VERSION="5.112.0"
NEOTERM_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NEOTERM_PKG_VERSION%.*}/kwidgetsaddons-${NEOTERM_PKG_VERSION}.tar.xz"
NEOTERM_PKG_SHA256=2b7a1cf73b99bbc7a95ef04c79971b8b5d8909e085815d0e04f452de08f8b574
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++, qt5-qtbase"
NEOTERM_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
