NEOTERM_SUBPKG_DESCRIPTION="Wheels for Python ensurepip"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_INCLUDE="
lib/python${_MAJOR_VERSION}/ensurepip/_bundled/
"
NEOTERM_SUBPKG_BREAKS="python (<< 3.11.1-3)"
NEOTERM_SUBPKG_REPLACES="python (<< 3.11.1-3)"
