NEOTERM_PKG_HOMEPAGE=https://muennich.github.io/id3ted/
NEOTERM_PKG_DESCRIPTION="A command line id3 tag editor"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.0
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://github.com/muennich/id3ted/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=b661514637278b00930cc13ef22f46530baadcf9f3f4ee4b7cb210b0d46b18f1
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="file, libc++, taglib"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX"
