NEOTERM_PKG_HOMEPAGE=https://znc.in/
NEOTERM_PKG_DESCRIPTION="An advanced IRC bouncer"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.9.0
NEOTERM_PKG_SRCURL=https://znc.in/releases/archive/znc-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=8b99c9dbb21c1309705073460be9bfacb6f7b0e83a15fe5d4b7140201b39d2a1
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
NEOTERM_PKG_DEPENDS="libc++, libicu, libsasl, openssl, zlib"
NEOTERM_PKG_FORCE_CMAKE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DWANT_I18N=OFF
"
