NEOTERM_PKG_HOMEPAGE=https://www.gaia-gis.it/fossil/freexl
NEOTERM_PKG_DESCRIPTION="Library to extract valid data from within an Excel (.xls) spreadsheet"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.0.0"
NEOTERM_PKG_SRCURL=https://www.gaia-gis.it/gaia-sins/freexl-sources/freexl-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=176705f1de58ab7c1eebbf5c6de46ab76fcd8b856508dbd28f5648f7c6e1a7f0
NEOTERM_PKG_DEPENDS="libiconv, libminizip, libexpat"
NEOTERM_PKG_GROUPS="science"
