NEOTERM_PKG_HOMEPAGE=https://tsl0922.github.io/ttyd/
NEOTERM_PKG_DESCRIPTION="Command-line tool for sharing terminal over the web"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.7.4"
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://github.com/tsl0922/ttyd/archive/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=300d8cef4b0b32b0ec30d7bf4d3721a5d180e22607f9467a95ab7b6d9652ca9b
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="json-c, libcap, libuv, libwebsockets, openssl, zlib"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DCMAKE_XXD=$NEOTERM_PKG_TMPDIR/xxd"
