NEOTERM_PKG_HOMEPAGE=https://flacon.github.io/
NEOTERM_PKG_DESCRIPTION="Extracts individual tracks from one big audio file and saves them as separate audio files"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="11.3.0"
NEOTERM_PKG_SRCURL=https://github.com/flacon/flacon/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=af8e90362ef2b2f1f1a0978b7d7ff7977e5875993579d2df793813e04d4cb31d
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++, libuchardet, qt5-qtbase, taglib"
NEOTERM_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
