NEOTERM_PKG_HOMEPAGE=https://libtins.github.io
NEOTERM_PKG_DESCRIPTION="High-level, multiplatform C++ network packet sniffing and crafting library."
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="4.5"
NEOTERM_PKG_SRCURL=https://github.com/mfontanini/libtins/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=6ff5fe1ada10daef8538743dccb9c9b3e19d05d028ffdc24838e62ff3fc55841
TRRMUX_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++, libpcap, openssl"
NEOTERM_PKG_BUILD_DEPENDS="boost, boost-headers"
NEOTERM_PKG_BREAKS="libtins-dev"
NEOTERM_PKG_REPLACES="libtins-dev"
