NEOTERM_PKG_HOMEPAGE=https://invisible-island.net/vile/
NEOTERM_PKG_DESCRIPTION="VI Like Emacs - vi work-alike"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_LICENSE_FILE="COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=9.8y
NEOTERM_PKG_SRCURL="https://invisible-island.net/archives/vile/current/vile-$NEOTERM_PKG_VERSION.tgz"
NEOTERM_PKG_SHA256=1b67f1ef34f5f2075722ab46184bb149735e8538fa912fc07c985c92f78fe381
NEOTERM_PKG_DEPENDS="ncurses"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
--disable-stripping
--without-iconv
"

neoterm_step_pre_configure() {
	CPPFLAGS+=" -DGETPGRP_VOID"
}
