NEOTERM_SUBPKG_DESCRIPTION="Platform-independent data for tvheadend"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_INCLUDE="share/tvheadend/"
NEOTERM_SUBPKG_DEPEND_ON_PARENT=no
NEOTERM_SUBPKG_BREAKS="tvheadend (<< 4.2.8-9)"
NEOTERM_SUBPKG_REPLACES="tvheadend (<< 4.2.8-9)"
