NEOTERM_SUBPKG_INCLUDE="share/help/"
NEOTERM_SUBPKG_DESCRIPTION="Gnumeric help files"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_BREAKS="gnumeric (<< 1.12.53)"
NEOTERM_SUBPKG_REPLACES="gnumeric (<< 1.12.53)"
