NEOTERM_PKG_HOMEPAGE=https://github.com/gabime/spdlog
NEOTERM_PKG_DESCRIPTION="Very fast, header-only/compiled, C++ logging library"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.13.0"
NEOTERM_PKG_SRCURL=https://github.com/gabime/spdlog/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=534f2ee1a4dcbeb22249856edfb2be76a1cf4f708a20b0ac2ed090ee24cfdbc9
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_BUILD_DEPENDS="fmt"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DSPDLOG_BUILD_SHARED=ON
-DSPDLOG_FMT_EXTERNAL=ON
"
