NEOTERM_SUBPKG_DESCRIPTION="Platform-independent data for lyx"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_INCLUDE="share/lyx/"
NEOTERM_SUBPKG_BREAKS="lyx (<< 2.3.7)"
NEOTERM_SUBPKG_REPLACES="lyx (<< 2.3.7)"
