NEOTERM_PKG_HOMEPAGE=https://github.com/mapbox/protozero
NEOTERM_PKG_DESCRIPTION="Minimalistic protocol buffer decoder and encoder in C++"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_LICENSE_FILE="LICENSE.md"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.7.1
NEOTERM_PKG_SRCURL=https://github.com/mapbox/protozero/archive/v${NEOTERM_PKG_VERSION}.zip
NEOTERM_PKG_SHA256=eb45bbad4c5e881e55f0d2c5175cc4a5068e9fff613a7c37479b0b94f94a7392
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DPYBIND11_FINDPYTHON=OFF"
