NEOTERM_SUBPKG_INCLUDE="share/help/"
NEOTERM_SUBPKG_DESCRIPTION="Evince help files"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_BREAKS="evince (<< 44.3)"
NEOTERM_SUBPKG_REPLACES="evince (<< 44.3)"
