NEOTERM_PKG_HOMEPAGE=https://www.netfilter.org/projects/libmnl/
NEOTERM_PKG_DESCRIPTION="a minimalistic user-space library oriented to Netlink developers"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.0.5
NEOTERM_PKG_SRCURL=https://netfilter.org/projects/libmnl/files/libmnl-${NEOTERM_PKG_VERSION}.tar.bz2
NEOTERM_PKG_SHA256=274b9b919ef3152bfb3da3a13c950dd60d6e2bcd54230ffeca298d03b40d0525
NEOTERM_PKG_BREAKS="libmnl-dev"
NEOTERM_PKG_REPLACES="libmnl-dev"
