NEOTERM_PKG_HOMEPAGE=https://github.com/folkertvanheusden/HTTPing
NEOTERM_PKG_DESCRIPTION="ping-like program for http-requests"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2.9
NEOTERM_PKG_SRCURL=https://github.com/folkertvanheusden/HTTPing/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=37da3c89b917611d2ff81e2f6c9e9de39d160ef0ca2cb6ffec0bebcb9b45ef5d
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_DEPENDS="fftw, libandroid-support, ncurses, openssl"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="--with-fftw3 --with-ncurses --with-openssl"
