NEOTERM_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="X11 font encoding library"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.1.7
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libfontenc-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=c0d36991faee06551ddbaf5d99266e97becdc05edfae87a833c3ff7bf73cfec2
NEOTERM_PKG_DEPENDS="zlib"
NEOTERM_PKG_BUILD_DEPENDS="xorgproto"
