NEOTERM_PKG_HOMEPAGE=https://www.pcre.org
NEOTERM_PKG_DESCRIPTION="Library implementing regular expression pattern matching using the same syntax and semantics as Perl 5"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=8.45
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://downloads.sourceforge.net/project/pcre/pcre/${NEOTERM_PKG_VERSION}/pcre-${NEOTERM_PKG_VERSION}.tar.bz2
NEOTERM_PKG_SHA256=4dae6fdcd2bb0bb6c37b5f97c33c2be954da743985369cddac3546e3218bffb8
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_BREAKS="pcre-dev"
NEOTERM_PKG_REPLACES="pcre-dev"
NEOTERM_PKG_RM_AFTER_INSTALL="bin/pcretest share/man/man1/pcretest.1"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="--enable-cpp --enable-jit --enable-utf8 --enable-unicode-properties"
