NEOTERM_PKG_HOMEPAGE=http://www.fefe.de/libowfat/
NEOTERM_PKG_DESCRIPTION="GPL reimplementation of libdjb"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.33
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://www.fefe.de/libowfat/libowfat-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=311ec8b3f4b72bb442e323fb013a98f956fa745547f2bc9456287b20d027cd7d
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_NO_STATICSPLIT=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="
prefix=$NEOTERM_PREFIX
LIBDIR=$NEOTERM_PREFIX/lib
MAN3DIR=$NEOTERM_PREFIX/share/man/man3
"
NEOTERM_MAKE_PROCESSES=1

neoterm_step_pre_configure() {
	# Use pregenerated entities.h.
	cp $NEOTERM_PKG_BUILDER_DIR/entities.h $NEOTERM_PKG_BUILDDIR/
	touch -d "next hour" $NEOTERM_PKG_BUILDDIR/entities.h
}
