NEOTERM_PKG_HOMEPAGE=https://www.raylib.com/
NEOTERM_PKG_DESCRIPTION="A simple and easy-to-use library to enjoy videogames programming"
NEOTERM_PKG_LICENSE="ZLIB"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.5.0
NEOTERM_PKG_SRCURL=https://github.com/raysan5/raylib/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=0df98bfc553db31356cab46a2f9ed6d932065f186a0fff24bafa05f8a60e16d1
NEOTERM_PKG_DEPENDS="glfw"
NEOTERM_PKG_BUILD_DEPENDS="glu, opengl"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DPLATFORM=Desktop
-DBUILD_EXAMPLES=OFF
-DBUILD_SHARED_LIBS=ON
-DUSE_EXTERNAL_GLFW=ON
-DOPENGL_VERSION=2.1
"
