NEOTERM_PKG_HOMEPAGE=https://github.com/pystardust/ytfzf
NEOTERM_PKG_DESCRIPTION="A POSIX script that helps you find Youtube videos (without API)"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.6.2"
NEOTERM_PKG_SRCURL=https://github.com/pystardust/ytfzf/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=73280e4ef4f490400a42bf582b713803c523587b0b30269859eaa6f2693ec9b1
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="curl, jq"
NEOTERM_PKG_RECOMMENDS="fzf, mpv"
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX"

neoterm_step_make() {
	:
}
