NEOTERM_PKG_HOMEPAGE=http://www.isthe.com/chongo/tech/comp/calc/
NEOTERM_PKG_DESCRIPTION="Arbitrary precision console calculator"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.15.0.5"
NEOTERM_PKG_SRCURL=https://github.com/lcn2/calc/releases/download/v$NEOTERM_PKG_VERSION/calc-$NEOTERM_PKG_VERSION.tar.bz2
NEOTERM_PKG_SHA256=4767a0247a1dbdc448a6bcb7390b8e625de2489b691575fa67d517c3377e63d4
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="ncurses, readline"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="LONG_BITS=$NEOTERM_ARCH_BITS"
NEOTERM_MAKE_PROCESSES=1
