NEOTERM_PKG_HOMEPAGE=https://www.opus-codec.org/
NEOTERM_PKG_DESCRIPTION="Utilities to encode and decode .opus files"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.2
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://downloads.xiph.org/releases/opus/opus-tools-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=b4e56cb00d3e509acfba9a9b627ffd8273b876b4e2408642259f6da28fa0ff86
NEOTERM_PKG_DEPENDS="libopusenc, libogg, libflac, opusfile, libopus"
