NEOTERM_PKG_HOMEPAGE=https://blogc.rgm.io/
NEOTERM_PKG_DESCRIPTION="A blog compiler"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="Rafael Martins @rafaelmartins"
NEOTERM_PKG_VERSION=0.20.1
NEOTERM_PKG_SRCURL=https://github.com/blogc/blogc/releases/download/v$NEOTERM_PKG_VERSION/blogc-$NEOTERM_PKG_VERSION.tar.bz2
NEOTERM_PKG_SHA256=0ecf95acbe9f90fc35986234c4feb8f860637a703cb50c7d0f054344ab9f6709
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="--disable-git-receiver --enable-make --enable-runserver --disable-tests --disable-valgrind"
