NEOTERM_PKG_HOMEPAGE=https://panotools.sourceforge.net/
NEOTERM_PKG_DESCRIPTION="Part of the Panorama Tools by Helmut Dersch"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.9.22"
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://downloads.sourceforge.net/panotools/libpano13-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=affc6830cdbe71c28d2731dcbf8dea2acda6d9ffd4609c6dbf3ba0c68440a8e3
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libjpeg-turbo, libpng, libtiff, zlib"
