NEOTERM_PKG_HOMEPAGE=https://docs.xfce.org/apps/xfce4-taskmanager/start
NEOTERM_PKG_DESCRIPTION="Easy to use task manager"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
_MAJOR_VERSION=1.5
NEOTERM_PKG_VERSION=${_MAJOR_VERSION}.5
NEOTERM_PKG_SRCURL=https://archive.xfce.org/src/apps/xfce4-taskmanager/${_MAJOR_VERSION}/xfce4-taskmanager-$NEOTERM_PKG_VERSION.tar.bz2
NEOTERM_PKG_SHA256=f64f01ba241a0b8bbf2ed3274e5decc2313c9f8b0e4d160db3ba69b331558ae5
NEOTERM_PKG_DEPENDS="gdk-pixbuf, glib, gtk3, libcairo, libwnck, libx11, libxfce4ui, libxfce4util, libxmu, xfconf"
