NEOTERM_PKG_HOMEPAGE=https://github.com/KhronosGroup/OpenCL-CLHPP
NEOTERM_PKG_DESCRIPTION="Khronos OpenCL C++ Headers"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2023.12.14"
NEOTERM_PKG_SRCURL=https://github.com/KhronosGroup/OpenCL-CLHPP/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=9106700634e79cfa0935ebd67197f64689ced24c42da702acf18fa8435bd8a82
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_DEPENDS="opencl-headers"
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTS=OFF
"
