NEOTERM_PKG_HOMEPAGE=https://gnupg.org/related_software/libksba/
NEOTERM_PKG_DESCRIPTION="Library for using X.509 certificates and CMS (Cryptographic Message Syntax) easily accessible"
NEOTERM_PKG_LICENSE="LGPL-3.0, GPL-3.0, GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.6.6"
NEOTERM_PKG_SRCURL=https://www.gnupg.org/ftp/gcrypt/libksba/libksba-${NEOTERM_PKG_VERSION}.tar.bz2
NEOTERM_PKG_SHA256=5dec033d211559338838c0c4957c73dfdc3ee86f73977d6279640c9cd08ce6a4
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libgpg-error"
NEOTERM_PKG_BREAKS="libksba-dev"
NEOTERM_PKG_REPLACES="libksba-dev"
