NEOTERM_PKG_HOMEPAGE=https://github.com/petervanderdoes/gitflow/
NEOTERM_PKG_DESCRIPTION="Extend git with Vincent Driessen's branching model. The AVH Edition adds more functionality."
NEOTERM_PKG_LICENSE="LGPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.12.3
NEOTERM_PKG_REVISION=9
NEOTERM_PKG_SRCURL=https://github.com/petervanderdoes/gitflow/archive/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=54e9fd81aa1aa8215c865503dc6377da205653c784d6c97baad3dafd20728e06
NEOTERM_PKG_DEPENDS="dash, git"
NEOTERM_PKG_EXTRA_MAKE_ARGS="prefix=$NEOTERM_PREFIX"
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_BUILD_IN_SRC=true
