NEOTERM_PKG_HOMEPAGE=https://fcitx-im.org/
NEOTERM_PKG_DESCRIPTION="Fcitx gtk library"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="5.1.2"
NEOTERM_PKG_SRCURL=https://github.com/fcitx/fcitx5-gtk/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=e40d274f899a31e0253d27220bd5c16e9859bb1efb585d26f174ee35fde080e4
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="glib"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DENABLE_GIR=OFF
-DENABLE_GTK2_IM_MODULE=ON
-DENABLE_GTK3_IM_MODULE=ON
-DENABLE_GTK4_IM_MODULE=ON
"
