NEOTERM_PKG_HOMEPAGE=https://www.gnu.org/software/stow/
NEOTERM_PKG_DESCRIPTION="Tool for managing the installation of multiple software packages into a single directory"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2.3.1
NEOTERM_PKG_SRCURL=https://fossies.org/linux/misc/stow-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=09d5d99671b78537fd9b2c0b39a5e9761a7a0e979f6fdb7eabfa58ee45f03d4b
NEOTERM_PKG_DEPENDS="perl"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
