NEOTERM_PKG_HOMEPAGE=https://github.com/theZiz/aha
NEOTERM_PKG_DESCRIPTION="Converts ANSI escape sequences of a unix terminal to HTML code"
# License: MPL-1.1 or LGPL-2.0-or-later
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_LICENSE_FILE="LICENSE.MPL1.1, LICENSE.LGPLv2+"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.5.1
NEOTERM_PKG_SRCURL=https://github.com/theZiz/aha/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=6aea13487f6b5c3e453a447a67345f8095282f5acd97344466816b05ebd0b3b1
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX"
