NEOTERM_SUBPKG_DESCRIPTION="QEMU Linux user mode emulator"
NEOTERM_SUBPKG_DEPENDS="glib, libandroid-shmem, libgnutls, libpixman"
NEOTERM_SUBPKG_DEPEND_ON_PARENT=no
NEOTERM_SUBPKG_BREAKS="qemu-user-x86_64"
NEOTERM_SUBPKG_REPLACES="qemu-user-x86_64"
NEOTERM_SUBPKG_INCLUDE="bin/qemu-x86_64"
