NEOTERM_PKG_HOMEPAGE=https://fatsort.sourceforge.io/
NEOTERM_PKG_DESCRIPTION="A C utility that sorts FAT12, FAT16, FAT32 and exFAT partitions"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.6.5.640
NEOTERM_PKG_SRCURL=https://downloads.sourceforge.net/fatsort/fatsort-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=630ece56d9eb3a55524af0aec3aade7854360eba949172a6cfb4768cb8fbe42e
NEOTERM_PKG_DEPENDS="libiconv"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="
MANDIR=$NEOTERM_PREFIX/share/man/man1
SBINDIR=$NEOTERM_PREFIX/bin
"

neoterm_step_pre_configure() {
	CFLAGS+=" $CPPFLAGS"
	LDFLAGS+=" -liconv"
}
