NEOTERM_PKG_HOMEPAGE="https://codemadness.org/sfeed-simple-feed-parser.html"
NEOTERM_PKG_DESCRIPTION="Shell-script/crontab oriented feed aggregator and parser utility (curses-based reader included)"
NEOTERM_PKG_LICENSE="ISC"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.0"
NEOTERM_PKG_SRCURL="https://codemadness.org/releases/sfeed/sfeed-$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=8e6a7e6e1d7e86034ae27035e37a8f7fc98bc25fe35120bd18ff07e04f18e91d
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="ncurses"
NEOTERM_PKG_RECOMMENDS="curl"
NEOTERM_PKG_SUGGESTS="lynx, neoterm-tools"
NEOTERM_PKG_BUILD_IN_SRC=true
