NEOTERM_PKG_HOMEPAGE=https://www.passwordstore.org
NEOTERM_PKG_DESCRIPTION="Lightweight directory-based password manager"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.7.4
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://git.zx2c4.com/password-store/snapshot/password-store-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=cfa9faf659f2ed6b38e7a7c3fb43e177d00edbacc6265e6e32215ff40e3793c0
NEOTERM_PKG_DEPENDS="bash, coreutils, gnupg (>= 2.2.9-1), tree"
NEOTERM_PKG_RECOMMENDS="git"
NEOTERM_PKG_SUGGESTS="pass-otp"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="WITH_ALLCOMP=yes"
