NEOTERM_SUBPKG_INCLUDE="lib/xorg/protocol.txt"
NEOTERM_SUBPKG_DESCRIPTION="X.Org protocol.txt file"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_DEPEND_ON_PARENT=no
NEOTERM_SUBPKG_REPLACES="xorg-server-xvfb (<< 1.20.11-8)"
NEOTERM_SUBPKG_BREAKS="xorg-server-xvfb (<< 1.20.11-8)"
