NEOTERM_PKG_HOMEPAGE=https://github.com/eja/eja
NEOTERM_PKG_DESCRIPTION="eja micro web server"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=13.11.25
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://github.com/eja/eja/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=eef4baa08e5fd71af871be3c00e70a1f12b95a22ea868cc219fd0eab71ff9e1b
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="DESTDIR=${NEOTERM_PREFIX} EJA_PATH=${NEOTERM_PREFIX} EJA_PATH_BIN=${NEOTERM_PREFIX}/bin EJA_PATH_LIB=${NEOTERM_PREFIX}/lib prefix=/"
NEOTERM_PKG_BUILD_IN_SRC=true
