NEOTERM_PKG_HOMEPAGE=https://github.com/ArthurSonzogni/FTXUI
NEOTERM_PKG_DESCRIPTION="A simple C++ library for terminal based user interface"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="5.0.0"
NEOTERM_PKG_SRCURL=https://github.com/ArthurSonzogni/FTXUI/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=a2991cb222c944aee14397965d9f6b050245da849d8c5da7c72d112de2786b5b
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
NEOTERM_PKG_AUTO_UPDATE=true
