NEOTERM_PKG_HOMEPAGE=https://github.com/dylanaraps/fff
NEOTERM_PKG_DESCRIPTION="A simple file manager written in bash"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2.2
NEOTERM_PKG_SRCURL=https://github.com/dylanaraps/fff/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=45f6e1091986c892ea45e1ac82f2d7f5417cfb343dc569d2625b5980e6bcfb62
NEOTERM_PKG_DEPENDS="bash"
NEOTERM_PKG_SUGGESTS="w3m-img, xdotool"
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX"
