NEOTERM_PKG_HOMEPAGE=https://github.com/xiph/libopusenc
NEOTERM_PKG_DESCRIPTION="High-level API for encoding .opus files"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.2.1
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://archive.mozilla.org/pub/opus/libopusenc-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=8298db61a8d3d63e41c1a80705baa8ce9ff3f50452ea7ec1c19a564fe106cbb9
NEOTERM_PKG_DEPENDS="libopus"
NEOTERM_PKG_BREAKS="libopusenc-dev"
NEOTERM_PKG_REPLACES="libopusenc-dev"
