NEOTERM_PKG_HOMEPAGE=https://github.com/google/flatbuffers
NEOTERM_PKG_DESCRIPTION="Memory Efficient Serialization Library"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="Simeon Huang <symeon@librehat.com>"
NEOTERM_PKG_VERSION="24.3.7"
NEOTERM_PKG_SRCURL=https://github.com/google/flatbuffers/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=bfff9d2150fcff88f844e8c608b02b2a0e94c92aea39b04c0624783464304784
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++"

NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DFLATBUFFERS_BUILD_SHAREDLIB=ON
-DFLATBUFFERS_BUILD_TESTS=OFF
"
