NEOTERM_PKG_HOMEPAGE=http://php.net/apcu
NEOTERM_PKG_DESCRIPTION="APCu - APC User Cache"
NEOTERM_PKG_LICENSE="PHP-3.01"
NEOTERM_PKG_LICENSE_FILE=LICENSE
NEOTERM_PKG_MAINTAINER="ian4hu <hu2008yinxiang@163.com>"
NEOTERM_PKG_VERSION="5.1.23"
NEOTERM_PKG_SRCURL="https://github.com/krakjoe/apcu/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_DEPENDS="php"
NEOTERM_PKG_SHA256=1adcb23bb04d631ee410529a40050cdd22afa9afb21063aa38f7b423f8a8335b
NEOTERM_PKG_AUTO_UPDATE=true

neoterm_step_pre_configure() {
	$NEOTERM_PREFIX/bin/phpize
	LDFLAGS+=" -landroid-shmem"
}
