NEOTERM_SUBPKG_INCLUDE="opt/openjdk/lib/src.zip"
NEOTERM_SUBPKG_DESCRIPTION="Source files for openjdk-17"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_DEPEND_ON_PARENT=no
NEOTERM_SUBPKG_CONFLICTS="openjdk-17 (<< 17.0-25)"
