NEOTERM_PKG_HOMEPAGE=https://github.com/Tencent/rapidjson/
NEOTERM_PKG_DESCRIPTION="fast JSON parser/generator for C++ with SAX/DOM style API"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.1.0
NEOTERM_PKG_REVISION=4
NEOTERM_PKG_SRCURL=https://github.com/Tencent/rapidjson/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DRAPIDJSON_BUILD_EXAMPLES=OFF"
