NEOTERM_PKG_HOMEPAGE=http://dushistov.github.io/sdcv/
NEOTERM_PKG_DESCRIPTION="StarDict Console Version"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.5.5
NEOTERM_PKG_SRCURL=https://github.com/Dushistov/sdcv/archive/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=4d2519e8f8479b9301dc91e9cda3e1eefef19970ece0e8c05f0c7b7ade5dc94b
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="glib, libc++, readline, zlib"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DENABLE_NLS=off"
