NEOTERM_PKG_HOMEPAGE=https://github.com/CNugteren/CLBlast
NEOTERM_PKG_DESCRIPTION="Tuned OpenCL BLAS"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.6.2"
NEOTERM_PKG_SRCURL=https://github.com/CNugteren/CLBlast/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=d7c1fb61162a6e2fa4eb6e95fafacbe22ee8460cd82371478f794f195aad267f
NEOTERM_PKG_DEPENDS="libc++, ocl-icd"
NEOTERM_PKG_BUILD_DEPENDS="opencl-headers"
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DNETLIB=ON
"
