NEOTERM_PKG_HOMEPAGE=https://gdal.org
NEOTERM_PKG_DESCRIPTION="A translator library for raster and vector geospatial data formats"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_LICENSE_FILE="LICENSE.TXT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="3.8.4"
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://download.osgeo.org/gdal/${NEOTERM_PKG_VERSION}/gdal-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=0c53ced95d29474236487202709b49015854f8e02e35e44ed0f4f4e12a7966ce
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="giflib, json-c, libc++, libcurl, libexpat, libfreexl, libgeos, libiconv, libjpeg-turbo, libjxl, liblzma, libpng, libspatialite, libsqlite, libwebp, libxml2, netcdf-c, openjpeg, openssl, proj, postgresql, zlib, zstd"
NEOTERM_PKG_BUILD_DEPENDS="json-c-static"
NEOTERM_PKG_BREAKS="gdal-dev"
NEOTERM_PKG_REPLACES="gdal-dev"
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DGDAL_USE_JXL=ON
-DGDAL_USE_TIFF_INTERNAL=ON
-DGDAL_USE_GEOTIFF_INTERNAL=ON
-DBUILD_PYTHON_BINDINGS=OFF
"
