NEOTERM_PKG_HOMEPAGE=http://www.grinninglizard.com/tinyxml2/
NEOTERM_PKG_DESCRIPTION="A simple, small, efficient, C++ XML parser"
NEOTERM_PKG_LICENSE="ZLIB"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="10.0.0"
NEOTERM_PKG_SRCURL=https://github.com/leethomason/tinyxml2/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=3bdf15128ba16686e69bce256cc468e76c7b94ff2c7f391cc5ec09e40bff3839
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
