NEOTERM_PKG_HOMEPAGE="https://github.com/file-acomplaint/simuwaerm"
NEOTERM_PKG_DESCRIPTION="A simple heat transfer simulator in pure Rust"
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.02"
NEOTERM_PKG_SRCURL="https://github.com/file-acomplaint/simuwaerm/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=cf3d86e9883e917b9c74ff3d1fc9146197b216b5aa84e84cc188326c8d922ac0
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
