NEOTERM_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="Display information utility for X"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.3.4
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/app/xdpyinfo-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=a8ada581dbd7266440d7c3794fa89edf6b99b8857fc2e8c31042684f3af4822b
NEOTERM_PKG_DEPENDS="libx11, libxcb, libxcomposite, libxext, libxi, libxinerama, libxrender, libxtst, libxxf86dga, libxxf86vm"
NEOTERM_PKG_BUILD_DEPENDS="xorg-util-macros"
