NEOTERM_PKG_HOMEPAGE=https://github.com/neoterm/neoterm-packages
NEOTERM_PKG_DESCRIPTION="A metapackage that installs at-spi2-core"
NEOTERM_PKG_LICENSE="Public Domain"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2.48.0
NEOTERM_PKG_AUTO_UPDATE=false
NEOTERM_PKG_SKIP_SRC_EXTRACT=true
NEOTERM_PKG_DEPENDS="at-spi2-core (>= 2.48.0)"
NEOTERM_PKG_METAPACKAGE=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
