NEOTERM_PKG_HOMEPAGE=https://gitlab.com/ecodis/exhale
NEOTERM_PKG_DESCRIPTION="Open source xHE-AAC encoder"
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_LICENSE_FILE="include/License.htm"
NEOTERM_PKG_MAINTAINER="@DLC01"
NEOTERM_PKG_VERSION=1.2.0.1
NEOTERM_PKG_SRCURL=https://gitlab.com/ecodis/exhale/-/archive/v${NEOTERM_PKG_VERSION}/exhale-v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=d2a58b5c38c3912b9990d2b1f2376a5664dcd25a2852494a0078e6b1a145ad4c
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
