NEOTERM_PKG_HOMEPAGE=https://github.com/WebAssembly/binaryen
NEOTERM_PKG_DESCRIPTION="Binaryen is a compiler and toolchain infrastructure library for WebAssembly"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="117"
NEOTERM_PKG_SRCURL=https://github.com/WebAssembly/binaryen/archive/version_${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=9acf7cc5be94bcd16bebfb93a1f5ac6be10e0995a33e1981dd7c404dafe83387
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+"
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_TESTS=OFF
-DBYN_ENABLE_LTO=ON
"
