NEOTERM_PKG_HOMEPAGE="https://github.com/yamafaktory/jql"
NEOTERM_PKG_DESCRIPTION="A JSON Query Language CLI tool"
NEOTERM_PKG_LICENSE="Apache-2.0, MIT"
NEOTERM_PKG_LICENSE_FILE="../../LICENSE-APACHE, ../../LICENSE-MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="7.1.6"
NEOTERM_PKG_SRCURL=https://github.com/yamafaktory/jql/archive/refs/tags/jql-v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=85f91131ae1305e73f688441c1b053c9126b045ebe9a3cb4e51d260f409a1688
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+.\d+.\d+"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_pre_configure() {
	NEOTERM_PKG_SRCDIR+="/crates/jql"
	NEOTERM_PKG_BUILDDIR="$NEOTERM_PKG_SRCDIR"
}
