NEOTERM_PKG_HOMEPAGE=https://www.gnu.org/software/bison/
NEOTERM_PKG_DESCRIPTION="General-purpose parser generator"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=3.8.2
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://mirrors.kernel.org/gnu/bison/bison-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2
NEOTERM_PKG_DEPENDS="m4"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
M4=m4
ac_cv_have_decl_posix_spawn=no
ac_cv_header_spawn_h=no
"

NEOTERM_PKG_RM_AFTER_INSTALL="share/info/dir"
NEOTERM_PKG_GROUPS="base-devel"
