NEOTERM_PKG_HOMEPAGE=https://mega.io/
NEOTERM_PKG_DESCRIPTION="Provides non UI access to MEGA services"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.6.3
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=git+https://github.com/meganz/MEGAcmd
NEOTERM_PKG_GIT_BRANCH=${NEOTERM_PKG_VERSION}_Linux
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
# dbus is required for $PREFIX/var/lib/dbus/machine-id
NEOTERM_PKG_DEPENDS="c-ares, cryptopp, dbus, ffmpeg, freeimage, libandroid-glob, libc++, libcurl, libsodium, libsqlite, libuv, mediainfo, openssl, pcre, readline, zlib"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
--disable-static
--with-pcre=$NEOTERM_PREFIX
ac_cv_lib_pthread_pthread_create=yes
"

neoterm_step_post_get_source() {
	# We use `config.h` generated by configure script instead of this one.
	local f="sdk/include/mega/config-android.h"
	if [ -f "${f}" ]; then
		rm -f "${f}"
		echo '#error DO NOT INCLUDE ME!' > "${f}"
	else
		neoterm_error_exit "Source file '${f}' not found."
	fi
}

neoterm_step_pre_configure() {
	autoreconf -fi

	export OBJCXX="$CXX"

	LDFLAGS+=" -landroid-glob"
	LDFLAGS+=" $($CC -print-libgcc-file-name)"

	# Fix build against FFmpeg 6.0:
	CPPFLAGS+=" -DCODEC_CAP_TRUNCATED=0"
}

neoterm_step_post_massage() {
	find lib -name '*.la' -delete
}
