NEOTERM_PKG_HOMEPAGE=https://www.gnu.org/software/enscript/
NEOTERM_PKG_DESCRIPTION="Enscript converts ASCII text files to PostScript, HTML, RTF, ANSI and overstrikes"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.6.6
NEOTERM_PKG_REVISION=12
NEOTERM_PKG_SRCURL=https://ftp.gnu.org/gnu/enscript/enscript-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=6d56bada6934d055b34b6c90399aa85975e66457ac5bf513427ae7fc77f5c0bb
NEOTERM_PKG_DEPENDS="cups, perl"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS=" --sysconfdir=$NEOTERM_PREFIX/etc/enscript"
