blank_issues_enabled: true
contact_links:
  - name: Want to add new mirrors? Mirror related issues?
    url: https://github.com/neoterm/neoterm-tools/issues
    about: Visit neoterm-tools issues page
  - name: Want to ask questions about the project?
    url: https://github.com/neoterm/neoterm-packages/discussions
    about: Join GitHub Discussions
