NEOTERM_PKG_HOMEPAGE=https://osm2pgsql.org/
NEOTERM_PKG_DESCRIPTION="osm2pgsql imports OpenStreetMap (OSM) data into a PostgreSQL/PostGIS database"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.11.0"
NEOTERM_PKG_SRCURL=https://github.com/openstreetmap/osm2pgsql/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=6b46313813b816f15ce906c04cd4108bbb05362740e0a1a8889055f4e25977d2
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="boost, libbz2, libc++, libexpat, liblua54, postgresql, proj, zlib, nlohmann-json"
NEOTERM_PKG_BLACKLISTED_ARCHES="arm, i686"
NEOTERM_PKG_BUILD_DEPENDS="boost-headers"
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DEXTERNAL_FMT=OFF
"
