NEOTERM_PKG_HOMEPAGE=https://www.portaudio.com/
NEOTERM_PKG_DESCRIPTION="A portable audio I/O library"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_LICENSE_FILE="LICENSE.txt"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=19.07.00
NEOTERM_PKG_REVISION=1
_DATE=20210406
NEOTERM_PKG_SRCURL=https://files.portaudio.com/archives/pa_stable_v${NEOTERM_PKG_VERSION//./}_${_DATE}.tgz
NEOTERM_PKG_SHA256=47efbf42c77c19a05d22e627d42873e991ec0c1357219c0d74ce6a2948cb2def
NEOTERM_PKG_AUTO_UPDATE=false
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
--enable-cxx
--without-alsa
--without-jack
--without-oss
--without-asihpi
ac_cv_lib_pthread_pthread_create=yes
ac_cv_lib_rt_clock_gettime=yes
"
NEOTERM_MAKE_PROCESSES=1
