NEOTERM_PKG_HOMEPAGE=https://invisible-island.net/byacc/
NEOTERM_PKG_DESCRIPTION="byacc is generally conceded to be the best yacc variant available"
NEOTERM_PKG_LICENSE="Public Domain"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=20230521
NEOTERM_PKG_SRCURL=https://invisible-island.net/archives/byacc/byacc-${NEOTERM_PKG_VERSION}.tgz
NEOTERM_PKG_SHA256=5ad915a7d5833aa38a5e31bd077505666029c35e365dff8569fe4598eaa9fef2
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_BUILD_DEPENDS="groff"
NEOTERM_PKG_CONFLICTS="bison"
NEOTERM_PKG_REPLACES="bison"
