NEOTERM_PKG_HOMEPAGE="https://neurobin.org/projects/softwares/unix/shc/"
NEOTERM_PKG_DESCRIPTION="Shell script compiler"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="Krishna Kanhaiya @kcubeterm"
NEOTERM_PKG_VERSION=4.0.3
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://github.com/neurobin/shc/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=7d7fa6a9f5f53d607ab851d739ae3d3b99ca86e2cb1425a6cab9299f673aee16
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="clang"
