NEOTERM_PKG_HOMEPAGE=https://xiph.org/flac/
NEOTERM_PKG_DESCRIPTION="FLAC (Free Lossless Audio Codec) library"
NEOTERM_PKG_LICENSE="GPL-2.0, LGPL-2.1, BSD 3-Clause"
NEOTERM_PKG_LICENSE_FILE="COPYING.GPL, COPYING.LGPL, COPYING.Xiph"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.4.3
NEOTERM_PKG_SRCURL=https://downloads.xiph.org/releases/flac/flac-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=6c58e69cd22348f441b861092b825e591d0b822e106de6eb0ee4d05d27205b70
NEOTERM_PKG_DEPENDS="libc++, libogg"
NEOTERM_PKG_BREAKS="libflac-dev"
NEOTERM_PKG_REPLACES="libflac-dev"
NEOTERM_PKG_RM_AFTER_INSTALL="
share/doc/flac/FLAC.tag
share/doc/flac/api/
"
