NEOTERM_PKG_HOMEPAGE=https://github.com/kraxarn/spotify-qt
NEOTERM_PKG_DESCRIPTION="Lightweight Spotify client using Qt"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=3.10
NEOTERM_PKG_SRCURL=https://github.com/kraxarn/spotify-qt/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=66191fc75f8571f40be16582caded2e6e3181434cbab5e85d3e9613c97ecb44f
NEOTERM_PKG_DEPENDS="libc++, qt5-qtbase, qt5-qtsvg"
NEOTERM_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools"
