NEOTERM_PKG_HOMEPAGE=https://www.gnu.org/software/units/
NEOTERM_PKG_DESCRIPTION="Converts between different systems of units"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2.22
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://mirrors.kernel.org/gnu/units/units-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=5d13e1207721fe7726d906ba1d92dc0eddaa9fc26759ed22e3b8d1a793125848
NEOTERM_PKG_DEPENDS="readline, libandroid-support"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
--sharedstatedir=$NEOTERM_PREFIX/var/lib
"
