NEOTERM_PKG_HOMEPAGE=https://www.blosc.org
NEOTERM_PKG_DESCRIPTION="A blocking, shuffling and loss-less compression library"
NEOTERM_PKG_LICENSE="BSD"
NEOTERM_PKG_LICENSE_FILE="\
LICENSES/BITSHUFFLE.txt
LICENSES/FASTLZ.txt
LICENSES/LZ4.txt
LICENSES/SNAPPY.txt
LICENSES/STDINT.txt
LICENSES/ZLIB-NG.txt
LICENSES/ZLIB.txt"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.21.5"
NEOTERM_PKG_SRCURL=https://github.com/Blosc/c-blosc/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=32e61961bbf81ffea6ff30e9d70fca36c86178afd3e3cfa13376adec8c687509
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="liblz4, libsnappy, zlib, zstd"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DDEACTIVATE_LZ4=OFF
-DDEACTIVATE_SNAPPY=OFF
-DDEACTIVATE_ZLIB=OFF
-DDEACTIVATE_ZSTD=OFF
-DPREFER_EXTERNAL_LZ4=ON
-DPREFER_EXTERNAL_ZLIB=ON
-DPREFER_EXTERNAL_ZSTD=ON
"
