NEOTERM_PKG_HOMEPAGE=https://gitlab.gnome.org/GNOME/adwaita-icon-theme
NEOTERM_PKG_DESCRIPTION="GNOME standard icons"
NEOTERM_PKG_LICENSE="LGPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
_MAJOR_VERSION=45
NEOTERM_PKG_VERSION=${_MAJOR_VERSION}.0
NEOTERM_PKG_SRCURL=https://download.gnome.org/sources/adwaita-icon-theme/${_MAJOR_VERSION}/adwaita-icon-theme-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=2442bfb06f4e6cc95bf6e2682fdff98fa5eddc688751b9d6215c623cb4e42ff1
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="hicolor-icon-theme, librsvg"
NEOTERM_PKG_RM_AFTER_INSTALL="share/icons/Adwaita/icon-theme.cache"
