NEOTERM_PKG_HOMEPAGE=https://github.com/neoterm/neoterm-packages
NEOTERM_PKG_DESCRIPTION="A metapackage that installs essential development tools"
NEOTERM_PKG_LICENSE="Public Domain"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.1
NEOTERM_PKG_AUTO_UPDATE=false
NEOTERM_PKG_DEPENDS="clang, make, pkg-config"
NEOTERM_PKG_RECOMMENDS="autoconf, automake, bc, bison, cmake, flex, gperf, libtool, m4"
NEOTERM_PKG_SUGGESTS="git, golang, nodejs, patchelf, proot, python, ruby, rust, subversion"
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_SKIP_SRC_EXTRACT=true
NEOTERM_PKG_METAPACKAGE=true
