NEOTERM_PKG_HOMEPAGE=https://github.com/ivmai/libatomic_ops
NEOTERM_PKG_DESCRIPTION="Provides semi-portable access to hardware-provided atomic memory update operations"
NEOTERM_PKG_LICENSE="GPL-2.0, MIT"
NEOTERM_PKG_LICENSE_FILE="README.md, LICENSE"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="7.8.2"
NEOTERM_PKG_SRCURL=https://github.com/ivmai/libatomic_ops/releases/download/v${NEOTERM_PKG_VERSION}/libatomic_ops-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=d305207fe207f2b3fb5cb4c019da12b44ce3fcbc593dfd5080d867b1a2419b51
NEOTERM_PKG_AUTO_UPDATE=true
