NEOTERM_PKG_HOMEPAGE="https://github.com/bootandy/dust"
NEOTERM_PKG_DESCRIPTION="A more intuitive version of du in rust"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.9.0"
NEOTERM_PKG_SRCURL=https://github.com/bootandy/dust/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=70efd66e662fcd93bbc6cf2f8c3104a1de7e52090f709e9040a34bdc7c72ea9c
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
