NEOTERM_PKG_HOMEPAGE=https://www.gnu.org/software/ocrad/ocrad.html
NEOTERM_PKG_DESCRIPTION="Optical Character Recognition program based on a feature extraction method"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.28
NEOTERM_PKG_SRCURL=https://mirrors.kernel.org/gnu/ocrad/ocrad-${NEOTERM_PKG_VERSION}.tar.lz
NEOTERM_PKG_SHA256=34ccea576dbdadaa5979e6202344c3ff68737d829ca7b66f71c8497d36bbbf2e
NEOTERM_PKG_DEPENDS="libc++, libpng"
NEOTERM_PKG_BREAKS="ocrad-dev"
NEOTERM_PKG_REPLACES="ocrad-dev"
