NEOTERM_PKG_HOMEPAGE=https://github.com/juic3b0x/neoterm-exec
NEOTERM_PKG_DESCRIPTION="An execve() wrapper to make /bin and /usr/bin shebangs work"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1:1.1
NEOTERM_PKG_SRCURL=https://github.com/juic3b0x/neoterm-exec/archive/v${NEOTERM_PKG_VERSION:2}.tar.gz
NEOTERM_PKG_SHA256=cc28460a4934f2cd73ba2a41fcc1b44efd61dcd5484d9654254f05facc4c6269
NEOTERM_PKG_ESSENTIAL=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="NEOTERM_PREFIX=${NEOTERM_PREFIX} NEOTERM_BASE_DIR=${NEOTERM_BASE_DIR}"
NEOTERM_PKG_AUTO_UPDATE=true
