NEOTERM_PKG_HOMEPAGE=https://github.com/juic3b0x/neoterm-exec
NEOTERM_PKG_DESCRIPTION="An execve() wrapper to make /bin and /usr/bin shebangs work"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1:1.1
NEOTERM_PKG_SRCURL=https://github.com/juic3b0x/neoterm-exec/archive/v${NEOTERM_PKG_VERSION:2}.tar.gz
NEOTERM_PKG_SHA256=66f7002898d3556c80371b0390f45e8b04d5fdcfb45afccc5472b342acb29b9a
NEOTERM_PKG_ESSENTIAL=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="NEOTERM_PREFIX=${NEOTERM_PREFIX} NEOTERM_BASE_DIR=${NEOTERM_BASE_DIR}"
NEOTERM_PKG_AUTO_UPDATE=true
