TERMUX_PKG_HOMEPAGE=https://github.com/neoterm/neoterm-exec
TERMUX_PKG_DESCRIPTION="An execve() wrapper to make /bin and /usr/bin shebangs work"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@neoterm"
TERMUX_PKG_VERSION=1:1.0
TERMUX_PKG_SRCURL=https://repo.theworkjoy.com/v1.0.tar.gz
TERMUX_PKG_SHA256=66f7002898d3556c80371b0390f45e8b04d5fdcfb45afccc5472b342acb29b9a
TERMUX_PKG_ESSENTIAL=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="TERMUX_PREFIX=${TERMUX_PREFIX} TERMUX_BASE_DIR=${TERMUX_BASE_DIR}"
TERMUX_PKG_AUTO_UPDATE=true
