NEOTERM_PKG_HOMEPAGE=http://libpipeline.nongnu.org/
NEOTERM_PKG_DESCRIPTION="C library for manipulating pipelines of subprocesses in a flexible and convenient way"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.5.7
NEOTERM_PKG_SRCURL=https://download.savannah.nongnu.org/releases/libpipeline/libpipeline-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=b8b45194989022a79ec1317f64a2a75b1551b2a55bea06f67704cb2a2e4690b0
NEOTERM_PKG_BREAKS="libpipeline-dev"
NEOTERM_PKG_REPLACES="libpipeline-dev"
