NEOTERM_PKG_HOMEPAGE=http://code.kryo.se/iodine
NEOTERM_PKG_DESCRIPTION="Tunnel IPv4 data through a DNS server"
NEOTERM_PKG_LICENSE="ISC"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.8.0
NEOTERM_PKG_SRCURL=https://code.kryo.se/iodine/iodine-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=546e92cf8617f7970ea81c850b1063eb189c68c406d0c6a67e02c55e72e714c6
NEOTERM_PKG_DEPENDS="net-tools, zlib"
NEOTERM_PKG_EXTRA_MAKE_ARGS="prefix=$NEOTERM_PREFIX"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_pre_configure() {
	CPPFLAGS+=" -DANDROID"
	CFLAGS+=" $CPPFLAGS"
	LDFLAGS+=" -lz"
}
