NEOTERM_PKG_HOMEPAGE=https://github.com/Haivision/srt
NEOTERM_PKG_DESCRIPTION="Secure Reliable Transport (SRT) Protocol"
NEOTERM_PKG_LICENSE="MPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.5.3"
NEOTERM_PKG_SRCURL=https://github.com/Haivision/srt/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=befaeb16f628c46387b898df02bc6fba84868e86a6f6d8294755375b9932d777
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++, openssl"
NEOTERM_PKG_FORCE_CMAKE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_GNUTLS=OFF
-DENABLE_STATIC=OFF
-DENABLE_TESTING=OFF
-DENABLE_UNITTESTS=OFF
"
