NEOTERM_PKG_HOMEPAGE=https://github.com/dstosberg/odt2txt
NEOTERM_PKG_DESCRIPTION="Simple converter from OpenDocument Text to plain text"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.5
NEOTERM_PKG_REVISION=4
NEOTERM_PKG_SRCURL=https://github.com/dstosberg/odt2txt/archive/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=23a889109ca9087a719c638758f14cc3b867a5dcf30a6c90bf6a0985073556dd
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="libiconv, libzip, zlib"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="HAVE_LIBZIP=1 DESTDIR=$NEOTERM_PREFIX"
