NEOTERM_PKG_HOMEPAGE=https://www.fetchmail.info/
NEOTERM_PKG_DESCRIPTION="A remote-mail retrieval utility"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_LICENSE_FILE="COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=6.4.37
NEOTERM_PKG_SRCURL=https://sourceforge.net/projects/fetchmail/files/branch_${NEOTERM_PKG_VERSION:0:3}/fetchmail-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=4a182e5d893e9abe6ac37ae71e542651fce6d606234fc735c2aaae18657e69ea
NEOTERM_PKG_DEPENDS="openssl"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="--with-ssl=$NEOTERM_PREFIX"
NEOTERM_PKG_RM_AFTER_INSTALL="lib/python${NEOTERM_PYTHON_VERSION}/site-packages/__pycache__"
NEOTERM_PKG_PYTHON_COMMON_DEPS="wheel"
