NEOTERM_PKG_HOMEPAGE=https://www.music.mcgill.ca/~gary/rtmidi/
NEOTERM_PKG_DESCRIPTION="A set of C++ classes that provides a common API for realtime MIDI input/output"
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_LICENSE_FILE="LICENSE"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=5.0.0
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=48db0ed58c8c0e207b5d7327a0210b5bcaeb50e26387935d02829239b0f3c2b9
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_FORCE_CMAKE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DRTMIDI_API_ALSA=OFF
-DRTMIDI_API_JACK=OFF
"
