NEOTERM_PKG_HOMEPAGE=https://docs.xfce.org/apps/ristretto/start
NEOTERM_PKG_DESCRIPTION="The Ristretto Image Viewer is an application that can be used to view, and scroll through images."
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
_MAJOR_VERSION=0.13
NEOTERM_PKG_VERSION=${_MAJOR_VERSION}.1
NEOTERM_PKG_SRCURL=https://archive.xfce.org/src/apps/ristretto/${_MAJOR_VERSION}/ristretto-${NEOTERM_PKG_VERSION}.tar.bz2
NEOTERM_PKG_SHA256=d71affbf15245067124725b153c908a53208c4ca1ba2d4df1ec5a1308d53791e
NEOTERM_PKG_DEPENDS="file, gdk-pixbuf, glib, gtk3, libcairo, libexif, libx11, libxfce4ui, libxfce4util, pango, xfconf"
NEOTERM_PKG_RECOMMENDS="tumbler"
