NEOTERM_PKG_HOMEPAGE=https://github.com/radare/ired
NEOTERM_PKG_DESCRIPTION="Minimalist hexadecimal editor"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.6
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://github.com/radare/ired/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=c15d37b96b1a25c44435d824bd7ef1f9aea9dc191be14c78b689d3156312d58a
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_pre_configure() {
	CFLAGS+=" $LDFLAGS"
}
