NEOTERM_PKG_HOMEPAGE=https://libmateweather.mate-desktop.dev/
NEOTERM_PKG_DESCRIPTION="libmateweather is a libgnomeweather fork."
NEOTERM_PKG_LICENSE="LGPL-2.1, GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.28.0"
NEOTERM_PKG_SRCURL=https://github.com/mate-desktop/libmateweather/releases/download/v$NEOTERM_PKG_VERSION/libmateweather-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=9a9c1e219c7546087f318d31dbf5f180e29de733d1c819f1e1b6e4f69e0a6489
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="atk, gdk-pixbuf, glib, gtk3, harfbuzz, libcairo, libsoup, libxml2, pango, zlib"
