NEOTERM_PKG_HOMEPAGE=https://github.com/jhawthorn/fzy
NEOTERM_PKG_DESCRIPTION="A simple, fast fuzzy finder for the terminal"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="Krishna Kanhaiya @kcubeterm"
NEOTERM_PKG_VERSION=1.0
NEOTERM_PKG_SRCURL=https://github.com/jhawthorn/fzy/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=80257fd74579e13438b05edf50dcdc8cf0cdb1870b4a2bc5967bd1fdbed1facf
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
