NEOTERM_PKG_HOMEPAGE=https://github.com/realh/roxterm
NEOTERM_PKG_DESCRIPTION="ROXTerm is a terminal emulator based on the VTE library"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
NEOTERM_PKG_VERSION="3.14.3"
NEOTERM_PKG_SRCURL=https://github.com/realh/roxterm/archive/refs/tags/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=4f801371113ff33d6a53dfa77aef6c3d09d29620fcf27e844c755904f9776e5b
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="dbus, dbus-glib, glib, gtk3, libcairo, libvte, pango"
NEOTERM_PKG_BUILD_DEPENDS="xsltproc"
NEOTERM_PKG_BUILD_IN_SRC=true
