# X11 package
NEOTERM_PKG_HOMEPAGE=https://xcb.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="XML-XCB protocol descriptions"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.16.0"
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=a75a1848ad2a89a82d841a51be56ce988ff3c63a8d6bf4383ae3219d8d915119
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_CONFLICTS="xcbproto"
NEOTERM_PKG_REPLACES="xcbproto"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
PYTHON=python${NEOTERM_PYTHON_VERSION}
am_cv_python_pythondir=$NEOTERM_PYTHON_HOME/site-packages
"
