NEOTERM_PKG_HOMEPAGE=https://fcitx-im.org/
NEOTERM_PKG_DESCRIPTION="A generic input method framework"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="5.1.6"
NEOTERM_PKG_SRCURL=https://github.com/fcitx/fcitx5/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=eb2ba98fe85f4fe0b35f5f93910d8d264647acd1402b6bf9da132cf8c68213cc
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="dbus, enchant, fcitx5-data, gdk-pixbuf, iso-codes, json-c, libandroid-execinfo, libc++, libcairo, libevent, libexpat, libuuid, libxcb, libxkbcommon, libxkbfile, pango, xcb-imdkit, xcb-util, xcb-util-keysyms, xcb-util-wm, zlib"
NEOTERM_PKG_BUILD_DEPENDS="extra-cmake-modules, fmt"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DDL_INCLUDE_DIR=$NEOTERM_PREFIX/include
-DPTHREAD_INCLUDE_DIR=$NEOTERM_PREFIX/include
-DENABLE_TEST=OFF
-DENABLE_WAYLAND=OFF
"
