NEOTERM_SUBPKG_DESCRIPTION="Rust compiler development libs"
NEOTERM_SUBPKG_DEPEND_ON_PARENT=no
NEOTERM_SUBPKG_BREAKS="rust (<< 1.74.1-1)"
NEOTERM_SUBPKG_REPLACES="rust (<< 1.74.1-1)"
NEOTERM_SUBPKG_INCLUDE="${_INCLUDED-}"
