NEOTERM_SUBPKG_DESCRIPTION="Rust std for target wasm32-unknown-unknown"
NEOTERM_SUBPKG_DEPEND_ON_PARENT=no
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_BREAKS="rust-std-wasm32 (<< 1.74.1-1)"
NEOTERM_SUBPKG_REPLACES="rust-std-wasm32 (<< 1.74.1-1)"
NEOTERM_SUBPKG_INCLUDE="
lib/rustlib/wasm32-unknown-unknown
"
