# X11 package
NEOTERM_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="X transport library"
# Licenses: MIT, HPND
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_LICENSE_FILE="COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.5.0
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/xtrans-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=1ba4b703696bfddbf40bacf25bce4e3efb2a0088878f017a50e9884b0c8fb1bd
NEOTERM_PKG_NO_DEVELSPLIT=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
