NEOTERM_PKG_HOMEPAGE=https://lxqt.github.io
NEOTERM_PKG_DESCRIPTION="PCManFM-Qt is the file manager of LXQt"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="Simeon Huang <symeon@librehat.com>"
NEOTERM_PKG_VERSION="1.4.1"
NEOTERM_PKG_SRCURL="https://github.com/lxqt/pcmanfm-qt/releases/download/${NEOTERM_PKG_VERSION}/pcmanfm-qt-${NEOTERM_PKG_VERSION}.tar.xz"
NEOTERM_PKG_SHA256=0de6c9125e7d4250fc52e65bf102720b88edb91d88bc89c352d45b5cb0202986
NEOTERM_PKG_DEPENDS="libc++, qt5-qtbase, qt5-qtx11extras, libfm-qt, liblxqt, lxmenu-data, lxqt-menu-data"
NEOTERM_PKG_BUILD_DEPENDS="lxqt-build-tools, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
NEOTERM_PKG_AUTO_UPDATE=true
