NEOTERM_PKG_HOMEPAGE=https://www.libssh.org/
NEOTERM_PKG_DESCRIPTION="Tiny C SSH library"
NEOTERM_PKG_LICENSE="LGPL-2.1, BSD 2-Clause"
NEOTERM_PKG_LICENSE_FILE="BSD, COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.10.6"
NEOTERM_PKG_SRCURL=https://www.libssh.org/files/${NEOTERM_PKG_VERSION%.*}/libssh-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=1861d498f5b6f1741b6abc73e608478491edcf9c9d4b6630eef6e74596de9dc1
NEOTERM_PKG_DEPENDS="openssl, zlib"
NEOTERM_PKG_BREAKS="libssh-dev"
NEOTERM_PKG_REPLACES="libssh-dev"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DHAVE_ARGP_H=OFF
-DWITH_GSSAPI=OFF
"

neoterm_step_pre_configure() {
	CPPFLAGS+=" -D__USE_GNU"
}
