NEOTERM_PKG_HOMEPAGE=https://jcorporation.github.io/myMPD/
NEOTERM_PKG_DESCRIPTION="A standalone and lightweight web-based MPD client"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="14.1.0"
NEOTERM_PKG_SRCURL=https://github.com/jcorporation/myMPD/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=f4bdb265915384d9271426a7e53977e71094ab03c0b2be5df185a2976ce4c6e2
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libflac, libid3tag, liblua54, openssl, pcre2, resolv-conf"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DMATH_LIB=m
-DMYMPD_STARTUP_SCRIPT=OFF
"
NEOTERM_CMAKE_BUILD="Unix Makefiles"
