NEOTERM_PKG_HOMEPAGE=https://openal-soft.org/
NEOTERM_PKG_DESCRIPTION="Software implementation of the OpenAL API"
NEOTERM_PKG_LICENSE="LGPL-2.0, BSD 3-Clause"
NEOTERM_PKG_LICENSE_FILE="BSD-3Clause, COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.23.1
NEOTERM_PKG_SRCURL=https://github.com/kcat/openal-soft/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=dfddf3a1f61059853c625b7bb03de8433b455f2f79f89548cbcbd5edca3d4a4a
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_METHOD=repology
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_BREAKS="openal-soft-dev"
NEOTERM_PKG_REPLACES="openal-soft-dev"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DALSOFT_UTILS=ON
-DALSOFT_NO_CONFIG_UTIL=ON
-DALSOFT_EXAMPLES=ON
-DALSOFT_TESTS=OFF
-DALSOFT_REQUIRE_OPENSL=ON
"
neoterm_step_pre_configure() {
	NEOTERM_PKG_EXTRA_CONFIGURE_ARGS+=" -DOPENSL_LIBRARY=$NEOTERM_STANDALONE_TOOLCHAIN/sysroot/usr/lib/$NEOTERM_HOST_PLATFORM/$NEOTERM_PKG_API_LEVEL/libOpenSLES.so"
}
