NEOTERM_PKG_HOMEPAGE=http://www.catb.org/~esr/greed/
NEOTERM_PKG_DESCRIPTION="Game where you try to eat as much as possible of the board before munching yourself into a corner"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.2
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=http://www.catb.org/~esr/greed/greed-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=702bc0314ddedb2ba17d4b55d873384a1606886e8d69f35ce67f6e3024a8d3fd
NEOTERM_PKG_DEPENDS="ncurses"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_GROUPS="games"
