NEOTERM_PKG_HOMEPAGE=http://t-sato.in.coocan.jp/xvkbd/
NEOTERM_PKG_DESCRIPTION="Virtual keyboard for X window system"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.1
NEOTERM_PKG_SRCURL=http://t-sato.in.coocan.jp/xvkbd/xvkbd-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=952d07df0fe1e45286520b7c98b4fd00fd60dbf3e3e8ff61e12c259f76a3bef4
NEOTERM_PKG_DEPENDS="libx11, libxaw, libxmu, libxt, libxtst"
NEOTERM_PKG_BUILD_DEPENDS="xorgproto"
NEOTERM_PKG_BUILD_IN_SRC=true
