NEOTERM_PKG_HOMEPAGE=https://capnproto.org/
NEOTERM_PKG_DESCRIPTION="Data interchange format and capability-based RPC system"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.0.2"
NEOTERM_PKG_SRCURL=https://capnproto.org/capnproto-c++-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=9057dbc0223366b74bbeca33a05de164a229b0377927f1b7ef3828cdd8cb1d7e
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_FORCE_CMAKE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
-DWITH_FIBERS=OFF
"
