NEOTERM_PKG_HOMEPAGE=https://dunst-project.org/
NEOTERM_PKG_DESCRIPTION="Lightweight and customizable notification daemon"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.9.2
NEOTERM_PKG_SRCURL=https://github.com/dunst-project/dunst/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz 
NEOTERM_PKG_SHA256=fa6ce45c0af4bae188b0d679a5ba92f8f9b7e4301bb1bb476e82df26bce9e71a
NEOTERM_PKG_DEPENDS="dbus, gdk-pixbuf, glib, libcairo, libnotify, libx11, libxext, libxinerama, libxrandr, libxss, pango"
NEOTERM_PKG_BUILD_IN_SRC=true
