NEOTERM_PKG_HOMEPAGE="https://www.cjmweb.net/vbindiff/"
NEOTERM_PKG_DESCRIPTION="Visual binary diff"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="3.0-beta5"
NEOTERM_PKG_SRCURL="http://deb.debian.org/debian/pool/main/v/vbindiff/vbindiff_$NEOTERM_PKG_VERSION.orig.tar.gz"
NEOTERM_PKG_SHA256=f04da97de993caf8b068dcb57f9de5a4e7e9641dc6c47f79b60b8138259133b8
NEOTERM_PKG_DEPENDS="libc++, ncurses, ncurses-ui-libs"
NEOTERM_PKG_BUILD_IN_SRC=true
