NEOTERM_PKG_HOMEPAGE=https://libsndfile.github.io/libsamplerate/
NEOTERM_PKG_DESCRIPTION="A library for performing sample rate conversion of audio data"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.2.2
NEOTERM_PKG_SRCURL=https://github.com/libsndfile/libsamplerate/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=16e881487f184250deb4fcb60432d7556ab12cb58caea71ef23960aec6c0405a
NEOTERM_PKG_FORCE_CMAKE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DLIBSAMPLERATE_EXAMPLES=OFF
-DLIBSAMPLERATE_TESTS=OFF
"
