NEOTERM_PKG_HOMEPAGE=https://git.causal.agency/catgirl
NEOTERM_PKG_DESCRIPTION="A TLS-only terminal IRC client"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.2"
NEOTERM_PKG_SRCURL=https://git.causal.agency/catgirl/snapshot/catgirl-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=fb6d04a099303af05d278c705c1542e7ee61643c030d6a0b68dec5371080a3c7
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libandroid-support, libretls, ncurses, openssl"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
--mandir=$NEOTERM_PREFIX/share/man
"
NEOTERM_PKG_EXTRA_MAKE_ARGS="catgirl"
