NEOTERM_PKG_HOMEPAGE=https://ssdb.io/
NEOTERM_PKG_DESCRIPTION="A Redis compatible NoSQL database stored on disk"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.9.9
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://github.com/ideawu/ssdb/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=a32009950114984d6e468e10d964b0ef1e846077b69d7c7615715fdfa01aaf6e
NEOTERM_PKG_DEPENDS="leveldb, libc++"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX/opt/ssdb"

neoterm_step_pre_configure() {
	export TARGET_OS=OS_ANDROID_CROSSCOMPILE
}
