NEOTERM_PKG_HOMEPAGE="https://beltoforion.de/en/muparser"
NEOTERM_PKG_DESCRIPTION="An extensible high performance math expression parser library written in C++"
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.3.4"
NEOTERM_PKG_SRCURL="https://github.com/beltoforion/muparser/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=0c3fa54a3ebf36dda0ed3e7cd5451c964afbb15102bdbcba08aafb359a290121
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_AUTO_UPDATE=true
