NEOTERM_SUBPKG_DESCRIPTION="LADSPA plugin for Rubber Band"
NEOTERM_SUBPKG_INCLUDE="lib/ladspa/ share/ladspa/"
NEOTERM_SUBPKG_DEPENDS="ladspa-sdk"
NEOTERM_SUBPKG_BREAKS="rubberband (<< 3.1.2-1)"
NEOTERM_SUBPKG_REPLACES="rubberband (<< 3.1.2-1)"
