NEOTERM_PKG_HOMEPAGE=https://github.com/zsh-users/zsh-completions
NEOTERM_PKG_DESCRIPTION="Additional completion definitions for Zsh"
NEOTERM_PKG_LICENSE=custom
NEOTERM_PKG_LICENSE_FILE=LICENSE
NEOTERM_PKG_MAINTAINER=@neoterm
NEOTERM_PKG_VERSION="0.35.0"
NEOTERM_PKG_SRCURL=$NEOTERM_PKG_HOMEPAGE/archive/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=811bb4213622720872e08d6e0857f1dd7bc12ff7aa2099a170b76301a53f4fbe
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_DEPENDS=zsh
NEOTERM_PKG_PLATFORM_INDEPENDENT=true

neoterm_step_make_install() {
	install -Dm644 src/* -t "$NEOTERM_PREFIX/share/zsh/site-functions"
}
