NEOTERM_PKG_HOMEPAGE=https://codeberg.org/dnkl/fcft
NEOTERM_PKG_DESCRIPTION="A small font loading and glyph rasterization library"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="3.1.7"
NEOTERM_PKG_SRCURL=https://codeberg.org/dnkl/fcft/archive/${NEOTERM_PKG_VERSION[0]}.tar.gz
NEOTERM_PKG_SHA256=0e29ea7edca4cf6f0ac6b4f6427a4606c184b3d809071e7d2f56fcc226574d30
NEOTERM_PKG_DEPENDS="fontconfig, freetype, harfbuzz, libpixman, libwayland, libxkbcommon, utf8proc"
NEOTERM_PKG_BUILD_DEPENDS="libtllist"
