NEOTERM_PKG_HOMEPAGE=https://github.com/mtoyoda/sl
NEOTERM_PKG_DESCRIPTION="Tool curing your bad habit of mistyping"
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_VERSION=5.02
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://github.com/mtoyoda/sl/archive/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=1e5996757f879c81f202a18ad8e982195cf51c41727d3fea4af01fdcbbb5563a
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="ncurses"
NEOTERM_PKG_LICENSE_FILE="LICENSE"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_make_install() {
	install sl $NEOTERM_PREFIX/bin/
	cp sl.1 $NEOTERM_PREFIX/share/man/man1
}
