NEOTERM_PKG_HOMEPAGE=https://github.com/KeithDHedger/Xfce-Theme-Manager
NEOTERM_PKG_DESCRIPTION="Integrated theme manager for xfce4"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
NEOTERM_PKG_VERSION=3.8
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://github.com/KeithDHedger/Xfce-Theme-Manager/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=da4b6b0ea9b9acde30893358ce2c997f298ffc6fac32e84aab6fa141b7bf26eb
NEOTERM_PKG_DEPENDS="gdk-pixbuf, glib, gtk2, libcairo, libxcursor, xfconf"
NEOTERM_PKG_BUILD_DEPENDS="libxfce4ui"
NEOTERM_PKG_RECOMMENDS="unzip"
NEOTERM_PKG_BUILD_IN_SRC=true
