NEOTERM_PKG_HOMEPAGE=https://docs.xfce.org/panel-plugins/xfce4-timer-plugin/start
NEOTERM_PKG_DESCRIPTION="alarm and timer module for Xfce panel"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
_MAJOR_VERSION=1.7
NEOTERM_PKG_VERSION=${_MAJOR_VERSION}.2
NEOTERM_PKG_SRCURL=https://archive.xfce.org/src/panel-plugins/xfce4-timer-plugin/${_MAJOR_VERSION}/xfce4-timer-plugin-${NEOTERM_PKG_VERSION}.tar.bz2
NEOTERM_PKG_SHA256=feb3b8c2d39505e816683540a3226bd7bda870ccbcb4c7d0f6abfeeff5c58b7d
NEOTERM_PKG_DEPENDS="atk, gdk-pixbuf, glib, gtk3, harfbuzz, libcairo, libxfce4ui, libxfce4util, pango, xfce4-panel, zlib"
NEOTERM_PKG_BUILD_IN_SRC=true
