NEOTERM_PKG_HOMEPAGE=https://github.com/ryanmjacobs/c
NEOTERM_PKG_DESCRIPTION="Compile and execute C 'scripts' in one go!"
NEOTERM_PKG_LICENSE=MIT
NEOTERM_PKG_MAINTAINER=@neoterm
NEOTERM_PKG_VERSION=0.14
NEOTERM_PKG_SRCURL=$NEOTERM_PKG_HOMEPAGE/archive/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=2b66d79d0d5c60b8e6760dac734b8ec9a7d6a5e57f033b97086821b1985a870b
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_DEPENDS=bash
NEOTERM_PKG_PLATFORM_INDEPENDENT=true

neoterm_step_make_install() {
	local bin="$(basename $NEOTERM_PKG_HOMEPAGE)"
	install -D "$bin" -t "$NEOTERM_PREFIX/bin"
}
