NEOTERM_PKG_HOMEPAGE=https://darwinsys.com/file/
NEOTERM_PKG_DESCRIPTION="Command-line tool that tells you in words what kind of data a file contains"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=5.45
NEOTERM_PKG_SRCURL=ftp://ftp.astron.com/pub/file/file-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=fc97f51029bb0e2c9f4e3bffefdaf678f0e039ee872b9de5c002a6d09c784d82
NEOTERM_PKG_DEPENDS="zlib"
NEOTERM_PKG_BREAKS="file-dev"
NEOTERM_PKG_REPLACES="file-dev"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_func_mmap_fixed_mapped=yes"
NEOTERM_PKG_EXTRA_MAKE_ARGS="FILE_COMPILE=$NEOTERM_PKG_HOSTBUILD_DIR/src/file"
NEOTERM_PKG_HOSTBUILD=true
NEOTERM_PKG_GROUPS="base-devel"
