NEOTERM_PKG_HOMEPAGE=https://github.com/Matroska-Org/libebml
NEOTERM_PKG_DESCRIPTION="Extensible Binary Meta Language library"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.4.5"
NEOTERM_PKG_SRCURL=https://github.com/Matroska-Org/libebml/archive/release-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=86c99573cd0957884f26547d1a8fa0c979e4d6d57484dfd387345846e6720f49
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_METHOD=repology
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
