NEOTERM_PKG_HOMEPAGE=https://cgit.freedesktop.org/xcb/util-cursor
NEOTERM_PKG_DESCRIPTION="XCB cursor library"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.1.5"
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/lib/xcb-util-cursor-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=0e9c5446dc6f3beb8af6ebfcc9e27bcc6da6fe2860f7fc07b99144dfa568e93b
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libxcb, xcb-util-image, xcb-util-renderutil"
