NEOTERM_PKG_HOMEPAGE=https://docs.xfce.org/xfce/tumbler/start
NEOTERM_PKG_DESCRIPTION="Tumbler is a D-Bus service for applications to request thumbnails for various URI schemes and MIME type"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="4.18.2"
NEOTERM_PKG_SRCURL=https://archive.xfce.org/src/xfce/tumbler/${NEOTERM_PKG_VERSION%.*}/tumbler-$NEOTERM_PKG_VERSION.tar.bz2
NEOTERM_PKG_SHA256=b530eec635eac7f898c0d8d3a3ff79d76a145d3bed3e786d54b1ec058132be7a
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="freetype, gdk-pixbuf, glib, libcurl, libjpeg-turbo, libpng, libxfce4util"
NEOTERM_PKG_RM_AFTER_INSTALL="lib/systemd"
