NEOTERM_PKG_HOMEPAGE=https://www.opus-codec.org/
NEOTERM_PKG_DESCRIPTION="Reference implementation of the Opus codec"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.4
NEOTERM_PKG_SRCURL=https://github.com/xiph/opus/releases/download/v${NEOTERM_PKG_VERSION}/opus-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=c9b32b4253be5ae63d1ff16eea06b94b5f0f2951b7a02aceef58e3a3ce49c51f
NEOTERM_PKG_BREAKS="libopus-dev"
NEOTERM_PKG_REPLACES="libopus-dev"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="--disable-extra-programs"
