NEOTERM_PKG_HOMEPAGE=https://gitlab.com/timvisee/ffsend
NEOTERM_PKG_DESCRIPTION="A fully featured Firefox Send client"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.2.76
NEOTERM_PKG_SRCURL=https://gitlab.com/timvisee/ffsend/-/archive/v$NEOTERM_PKG_VERSION/ffsend-v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=82a55bbc1afce99093cd84b2c623bfeadd509dfd592fbdd961f1156c8a80b0bd
NEOTERM_PKG_DEPENDS="openssl"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="--no-default-features --features crypto-openssl,send2,send3,history,archive,qrcode,urlshorten,infer-command"
