NEOTERM_PKG_HOMEPAGE=https://github.com/solus-project/brisk-menu
NEOTERM_PKG_DESCRIPTION="An efficient menu for the MATE Desktop"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_VERSION=0.6.2
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
NEOTERM_PKG_SRCURL=http://deb.debian.org/debian/pool/main/b/brisk-menu/brisk-menu_$NEOTERM_PKG_VERSION.orig.tar.xz
NEOTERM_PKG_SHA256=5a87f4dcf7365e81a571128bf0b8199eb06a6fcd7e15ec7739be0ccff1326488
NEOTERM_PKG_DEPENDS="dconf, glib, gtk3, libnotify, libx11, mate-menus, mate-panel"
