NEOTERM_PKG_HOMEPAGE=http://software.clapper.org/daemonize/
NEOTERM_PKG_DESCRIPTION="Run a command as a Unix daemon"
NEOTERM_PKG_LICENSE="BSD 3-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.7.8
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://github.com/bmc/daemonize/archive/release-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=20c4fc9925371d1ddf1b57947f8fb93e2036eb9ccc3b43a1e3678ea8471c4c60
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_METHOD=repology
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_func_setpgrp_void=yes"
NEOTERM_PKG_EXTRA_MAKE_ARGS="INSTALL_SBIN=$NEOTERM_PREFIX/bin"
