NEOTERM_PKG_HOMEPAGE=https://github.com/radare/posixvala
NEOTERM_PKG_DESCRIPTION="Aims to bring back the posix profile for Vala"
NEOTERM_PKG_LICENSE="GPL-3.0, LGPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.2
NEOTERM_PKG_SRCURL=https://github.com/radare/posixvala/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=d35d1e333d7941e130e094b0f55d53132855b990a7df699c14061e0a0e6853e8
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX"

neoterm_step_make() {
	:
}
