NEOTERM_PKG_HOMEPAGE=https://github.com/tgraf/bmon
NEOTERM_PKG_DESCRIPTION="Bandwidth monitor and rate estimator"
NEOTERM_PKG_LICENSE="MIT, BSD 2-Clause"
NEOTERM_PKG_LICENSE_FILE="LICENSE.MIT, LICENSE.BSD"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.0
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://github.com/tgraf/bmon/archive/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=d5e503ff6b116c681ebf4d10e238604dde836dceb9c0008eb92416a96c87ca40
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libconfuse, libnl, ncurses"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_pre_configure() {
	./autogen.sh
}
