NEOTERM_PKG_HOMEPAGE=https://www.rarlab.com/
NEOTERM_PKG_DESCRIPTION="Tool for extracting files from .rar archives"
NEOTERM_PKG_LICENSE="non-free"
NEOTERM_PKG_LICENSE_FILE="license.txt"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=6.2.12
NEOTERM_PKG_SRCURL=https://www.rarlab.com/rar/unrarsrc-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=a008b5f949bca9bb4ffa1bebbfc8b3c14b89df10a10354809b845232d5f582e5
NEOTERM_PKG_DEPENDS="libandroid-support, libc++"
NEOTERM_PKG_BUILD_IN_SRC=true
