NEOTERM_PKG_HOMEPAGE=https://www.freedesktop.org/wiki/Software/uchardet/
NEOTERM_PKG_DESCRIPTION="An encoding detector library"
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_LICENSE_FILE="COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.0.8
NEOTERM_PKG_SRCURL=https://www.freedesktop.org/software/uchardet/releases/uchardet-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0
NEOTERM_PKG_DEPENDS="libc++"
