NEOTERM_PKG_HOMEPAGE=https://fcitx-im.org/
NEOTERM_PKG_DESCRIPTION="Fcitx Qt immodule & library"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="5.1.5"
NEOTERM_PKG_SRCURL=https://github.com/fcitx/fcitx5-qt/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=a0eac9e8ab55f66ee984ac8bee1f56acd9cda5411f991cde494a6eaefc6b5c6c
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="fcitx5, libc++, libx11, libxcb, libxkbcommon, qt5-qtbase"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DENABLE_TEST=OFF
-DENABLE_QT4=OFF
-DENABLE_QT5=ON
-DENABLE_QT6=OFF
"
