NEOTERM_PKG_HOMEPAGE=https://github.com/signalapp/libsignal-protocol-c
NEOTERM_PKG_DESCRIPTION="Signal Protocol C Library"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_VERSION=2.3.3
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_MAINTAINER="Oliver Schmidhauser @Neo-Oli"
NEOTERM_PKG_SRCURL=https://github.com/signalapp/libsignal-protocol-c/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=c22e7690546e24d46210ca92dd808f17c3102e1344cd2f9a370136a96d22319d
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="openssl"

neoterm_step_pre_configure() {
    NEOTERM_PKG_EXTRA_CONFIGURE_ARGS+=" -DBUILD_SHARED_LIBS=ON"
    NEOTERM_PKG_EXTRA_CONFIGURE_ARGS+=" -DM_LIB=$NEOTERM_STANDALONE_TOOLCHAIN/sysroot/usr/lib/$NEOTERM_HOST_PLATFORM/$NEOTERM_PKG_API_LEVEL/libm.so"
}
