NEOTERM_PKG_HOMEPAGE=https://github.com/neoterm/x11-packages
NEOTERM_PKG_DESCRIPTION="A metapackage that installs all parts of the XFCE desktop environment"
NEOTERM_PKG_LICENSE="Public Domain"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2.1
NEOTERM_PKG_REVISION=17
NEOTERM_PKG_AUTO_UPDATE=false
NEOTERM_PKG_SKIP_SRC_EXTRACT=true
NEOTERM_PKG_DEPENDS="thunar, xfce4-panel, xfce4-session, xfce4-settings, xfconf, xfwm4, xfce4-notifyd, xfce4-terminal"
NEOTERM_PKG_CONFLICTS="xfce"
NEOTERM_PKG_REPLACES="xfce"
NEOTERM_PKG_PROVIDES="xfce"
NEOTERM_PKG_METAPACKAGE=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
