NEOTERM_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="Classic X utility to set your root window background to a given pattern or color"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.1.3
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/app/xsetroot-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=6081b45a9eb4426e045d259d1e144b32417fb635e5b96aa90647365ac96638d1
NEOTERM_PKG_DEPENDS="libx11, libxcursor, libxmu"
NEOTERM_PKG_BUILD_DEPENDS="xbitmaps, xorg-util-macros"
