NEOTERM_PKG_HOMEPAGE=https://git.sr.ht/~sircmpwn/scdoc
NEOTERM_PKG_DESCRIPTION="Small man page generator"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="Yaksh Bariya <thunder-coding@neoterm.dev>"
NEOTERM_PKG_VERSION=1.11.3
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://git.sr.ht/~sircmpwn/scdoc/archive/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=4c5c6136540384e5455b250f768e7ca11b03fdba1a8efc2341ee0f1111e57612
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="OUTDIR=$NEOTERM_PKG_SRCDIR HOST_SCDOC=$NEOTERM_PKG_HOSTBUILD_DIR/scdoc"
NEOTERM_PKG_HOSTBUILD=true

neoterm_step_host_build() {
	cd $NEOTERM_PKG_SRCDIR
	make OUTDIR=$NEOTERM_PKG_HOSTBUILD_DIR
}
