NEOTERM_PKG_HOMEPAGE=https://git.zx2c4.com/music-file-organizer/about/
NEOTERM_PKG_DESCRIPTION="Organizer of audio files into directories based on metadata tags"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.0.4
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://git.zx2c4.com/music-file-organizer/snapshot/music-file-organizer-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=9e3e2df24c5293e14c40d85fb480f5d52c0dc9afac845280a356c2fb6531e43e
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_DEPENDS="libicu, taglib"
