NEOTERM_PKG_HOMEPAGE=https://xcb.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="Utility libraries for XC Binding - Port of Xlib's XImage and XShmImage functions"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.4.1
NEOTERM_PKG_SRCURL=https://xcb.freedesktop.org/dist/xcb-util-image-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=ccad8ee5dadb1271fd4727ad14d9bd77a64e505608766c4e98267d9aede40d3d
NEOTERM_PKG_DEPENDS="libxcb, xcb-util"
NEOTERM_PKG_BUILD_DEPENDS="xorg-util-macros"
