NEOTERM_SUBPKG_INCLUDE="share/povray-*/"
NEOTERM_SUBPKG_DESCRIPTION="Platform-independent data for povray"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_BREAKS="povray (<< 3.8.0-beta.2-2)"
NEOTERM_SUBPKG_REPLACES="povray (<< 3.8.0-beta.2-2)"
