NEOTERM_PKG_HOMEPAGE=https://github.com/hoedown/hoedown
NEOTERM_PKG_DESCRIPTION="Hoedown is a revived fork of Sundown, the Markdown parser based on the original code of the Upskirt library"
NEOTERM_PKG_LICENSE="ISC"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=3.0.7
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://github.com/hoedown/hoedown/archive/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=01b6021b1ec329b70687c0d240b12edcaf09c4aa28423ddf344d2bd9056ba920
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_BREAKS="hoedown-dev"
NEOTERM_PKG_REPLACES="hoedown-dev"
NEOTERM_PKG_BUILD_IN_SRC=true
