NEOTERM_PKG_HOMEPAGE=https://www.cgal.org/
NEOTERM_PKG_DESCRIPTION="Computational Geometry Algorithms Library"
NEOTERM_PKG_LICENSE="GPL-3.0, LGPL-3.0, BSL-1.0, MIT"
NEOTERM_PKG_LICENSE_FILE="LICENSE, LICENSE.BSL, LICENSE.GPL, LICENSE.LGPL, LICENSE.RFL"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="5.6.1"
NEOTERM_PKG_SRCURL=https://github.com/CGAL/cgal/releases/download/v${NEOTERM_PKG_VERSION}/CGAL-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=cdb15e7ee31e0663589d3107a79988a37b7b1719df3d24f2058545d1bcdd5837
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_GROUPS="science"

NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DWITH_CGAL_Qt5=OFF
-DWITH_demos=OFF
-DWITH_examples=OFF
-DWITH_tests=OFF
"
