NEOTERM_PKG_HOMEPAGE=https://github.com/martanne/dvtm
NEOTERM_PKG_DESCRIPTION="Terminal tiling window manager"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.15
NEOTERM_PKG_REVISION=3
NEOTERM_PKG_SRCURL=https://github.com/martanne/dvtm/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=496eada13d8abaa8d772279746f78b0c6fed11b560599490f3e70ebc21197bf0
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_DEPENDS="ncurses"

neoterm_step_pre_configure() {
	CFLAGS+=" $CPPFLAGS"
}
