NEOTERM_PKG_HOMEPAGE=https://weechat.org/
NEOTERM_PKG_DESCRIPTION="Fast, light and extensible IRC chat client"
NEOTERM_PKG_LICENSE="GPL-3.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
# `weechat-python-plugin` depends on libpython${NEOTERM_PYTHON_VERSION}.so.
# Please revbump and rebuild when bumping NEOTERM_PYTHON_VERSION.
NEOTERM_PKG_VERSION="4.2.1"
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://www.weechat.org/files/src/weechat-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=253ddf086f6c845031a2dd294b1552851d6b04cc08a2f9da4aedfb3e2f91bdcd
NEOTERM_PKG_DEPENDS="libandroid-support, libcurl, libgcrypt, libgnutls, libiconv, ncurses, zlib, zstd"
NEOTERM_PKG_BREAKS="weechat-dev"
NEOTERM_PKG_REPLACES="weechat-dev"
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_RM_AFTER_INSTALL="
bin/weechat-curses
share/icons
share/man/man1/weechat-headless.1
"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DCA_FILE=${NEOTERM_PREFIX}/etc/tls/cert.pem
-DGETTEXT_FOUND=ON
-DENABLE_GUILE=OFF
-DENABLE_HEADLESS=OFF
-DENABLE_JAVASCRIPT=OFF
-DENABLE_LUA=ON
-DENABLE_MAN=ON
-DENABLE_PERL=ON
-DENABLE_PYTHON3=ON
-DENABLE_PHP=OFF
-DENABLE_RUBY=ON
-DENABLE_SPELL=OFF
-DENABLE_TCL=OFF
-DENABLE_TESTS=OFF
-DLIBGCRYPT_CONFIG_EXECUTABLE=${NEOTERM_PREFIX}/bin/libgcrypt-config
-DMSGFMT_EXECUTABLE=$(command -v msgfmt)
-DMSGMERGE_EXECUTABLE=$(command -v msgmerge)
-DSTRICT=ON
-DXGETTEXT_EXECUTABLE=$(command -v xgettext)
"

neoterm_step_pre_configure() {
	NEOTERM_PKG_EXTRA_CONFIGURE_ARGS+=" -DPKG_CONFIG_EXECUTABLE=${PKG_CONFIG}"
}
