NEOTERM_PKG_HOMEPAGE="https://lexbor.com"
NEOTERM_PKG_DESCRIPTION="Fast embeddable web browser engine written in C with no dependencies"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.3.0"
NEOTERM_PKG_SRCURL="https://github.com/lexbor/lexbor/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=522ad446cd01d89cb870c6561944674e897f8ada523f234d5be1f8d2d7d236b7
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DLEXBOR_BUILD_SHARED=ON
-DLEXBOR_BUILD_STATIC=OFF
-DLEXBOR_BUILD_EXAMPLES=OFF
-DLEXBOR_BUILD_TESTS=OFF
-DLEXBOR_BUILD_TESTS_CPP=OFF
"

