NEOTERM_PKG_HOMEPAGE=http://caca.zoy.org/wiki/toilet
NEOTERM_PKG_DESCRIPTION="FIGlet-compatible display of large colourful characters in text mode"
NEOTERM_PKG_LICENSE="WTFPL"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.3
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=http://deb.debian.org/debian/pool/main/t/toilet/toilet_${NEOTERM_PKG_VERSION}.orig.tar.gz
NEOTERM_PKG_SHA256=89d4b530c394313cc3f3a4e07a7394fa82a6091f44df44dfcd0ebcb3300a81de
NEOTERM_PKG_DEPENDS="libcaca"
NEOTERM_PKG_BUILD_IN_SRC=true
