NEOTERM_PKG_HOMEPAGE=https://www.libsdl.org
NEOTERM_PKG_DESCRIPTION="Simple DirectMedia Layer (SDL) sdl12-compat"
NEOTERM_PKG_LICENSE="ZLIB"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.2.60
NEOTERM_PKG_SRCURL=https://github.com/libsdl-org/sdl12-compat/archive/refs/tags/release-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=029fa24fe9e0d6a15b94f4737a2d3ed3144c5ef920eb82b4c6b30248eb94518b
NEOTERM_PKG_DEPENDS="sdl2"
NEOTERM_PKG_CONFLICTS="libsdl"
NEOTERM_PKG_REPLACES="libsdl"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DSDL12TESTS=OFF
"
NEOTERM_PKG_NO_STATICSPLIT=true
