NEOTERM_PKG_HOMEPAGE=https://tomclegg.ca/mp3cat
NEOTERM_PKG_DESCRIPTION="Copies a byte stream, skipping everything except mp3 frames with valid headers"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.5
NEOTERM_PKG_SRCURL=https://github.com/tomclegg/mp3cat/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=b1ec915c09c7e1c0ff48f54844db273505bc0157163bed7b2940792dca8ff951
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_CONFLICTS="mp3cat-go"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="
PREFIX=$NEOTERM_PREFIX
INSTALL_COMMAND=install
"
