NEOTERM_PKG_HOMEPAGE=https://github.com/rfc1036/whois
NEOTERM_PKG_DESCRIPTION="An intelligent Whois client"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="5.5.21"
NEOTERM_PKG_SRCURL=https://github.com/rfc1036/whois/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=4366a1c5e0e3e3e696de833bfa2620f8107d8fec9fc044c4a616eb805b08cc77
NEOTERM_PKG_DEPENDS="libcrypt, libiconv, libidn2"
NEOTERM_PKG_CONFLICTS="inetutils (<< 1.9.4-13)"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="
prefix=$NEOTERM_PREFIX
HAVE_ICONV=1
"

NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"

neoterm_step_pre_configure() {
	CPPFLAGS+=" -DHAVE_CRYPT_H"
	LDFLAGS+=" -liconv"
}
