NEOTERM_PKG_HOMEPAGE="https://github.com/sirwart/ripsecrets"
NEOTERM_PKG_DESCRIPTION="A command-line tool to prevent committing secret keys into your source code"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.1.7"
NEOTERM_PKG_SRCURL="https://github.com/sirwart/ripsecrets/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=12e1dfcd217bba34f74fd639d1a8de7dcf93ff2ae69398e093dfd794811db3ca
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
