NEOTERM_PKG_HOMEPAGE="https://github.com/tbeu/matio"
NEOTERM_PKG_DESCRIPTION="A C library for reading and writing Matlab MAT files"
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.5.26"
NEOTERM_PKG_SRCURL="https://github.com/tbeu/matio/archive/refs/tags/v$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=4aa5ac827ee49a3111f88f8d9b8ae034b8757384477e8f29cb64582c7d54e156
NEOTERM_PKG_DEPENDS="zlib"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DMATIO_WITH_HDF5:BOOL=OFF
-DMATIO_MAT73:BOOL=OFF
-DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF
-DMATIO_SHARED:BOOL=ON
"
