NEOTERM_PKG_HOMEPAGE=https://www.unicorn-engine.org/
NEOTERM_PKG_DESCRIPTION="Unicorn is a lightweight multi-platform, multi-architecture CPU emulator framework"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="2.0.1.post1"
NEOTERM_PKG_SRCURL=https://github.com/unicorn-engine/unicorn/archive/$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=6b276c857c69ee5ec3e292c3401c8c972bae292e0e4cb306bb9e5466c0f14737
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BREAKS="unicorn-dev"
NEOTERM_PKG_REPLACES="unicorn-dev"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DNEOTERM_ARCH=$NEOTERM_ARCH"
