NEOTERM_PKG_HOMEPAGE=https://github.com/elfmz/far2l
NEOTERM_PKG_DESCRIPTION="FAR Manager v2"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@spvkgn"
NEOTERM_PKG_VERSION="2.6.0"
NEOTERM_PKG_SRCURL=https://github.com/elfmz/far2l/archive/v_${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=3d1c0c0a1dd4b899afd659876c9e636dbc5920cbce514dbfe9c0f6843ec2baee
NEOTERM_PKG_DEPENDS="libarchive, libc++, libuchardet, pcre"
NEOTERM_PKG_SUGGESTS="chafa, exiftool, htop, timg"
NEOTERM_PKG_RM_AFTER_INSTALL="share/icons share/applications"
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DANDROID=ON
-DUSEWX=OFF
-DCOLORER=OFF
"
