NEOTERM_PKG_HOMEPAGE=https://dns.lookup.dog/
NEOTERM_PKG_DESCRIPTION="A command-line DNS client"
NEOTERM_PKG_LICENSE="EUPL-1.2"
NEOTERM_PKG_LICENSE_FILE="LICENCE"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.1.0
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://github.com/ogham/dog/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=82387d38727bac7fcdb080970e84b36de80bfe7923ce83f993a77d9ac7847858
NEOTERM_PKG_DEPENDS="openssl-1.1, resolv-conf"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_pre_configure() {
	export OPENSSL_INCLUDE_DIR=$NEOTERM_PREFIX/include/openssl-1.1
	export OPENSSL_LIB_DIR=$NEOTERM_PREFIX/lib/openssl-1.1
	CFLAGS="-I$NEOTERM_PREFIX/include/openssl-1.1 $CFLAGS"
	CPPFLAGS="-I$NEOTERM_PREFIX/include/openssl-1.1 $CPPFLAGS"
	CXXFLAGS="-I$NEOTERM_PREFIX/include/openssl-1.1 $CXXFLAGS"
	LDFLAGS="-L$NEOTERM_PREFIX/lib/openssl-1.1 -Wl,-rpath=$NEOTERM_PREFIX/lib/openssl-1.1 $LDFLAGS"
	
	RUSTFLAGS+=" -C link-arg=-Wl,-rpath=$NEOTERM_PREFIX/lib/openssl-1.1"
}
