NEOTERM_PKG_HOMEPAGE="https://github.com/Gecode/gecode"
NEOTERM_PKG_DESCRIPTION="Generic Constraint Development Environment"
NEOTERM_PKG_GROUPS="science"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="6.2.0"
NEOTERM_PKG_SRCURL="https://github.com/Gecode/gecode/archive/refs/tags/release-$NEOTERM_PKG_VERSION.tar.gz"
NEOTERM_PKG_SHA256=27d91721a690db1e96fa9bb97cec0d73a937e9dc8062c3327f8a4ccb08e951fd
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
NEOTERM_PKG_DEPENDS="libc++"
NEOTERM_PKG_FORCE_CMAKE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DENABLE_GIST=OFF
-DENABLE_CPPROFILER=OFF
-DBUILD_EXAMPLES=OFF
"
