NEOTERM_PKG_HOMEPAGE=https://github.com/holman/spark
NEOTERM_PKG_DESCRIPTION="▁▂▃▅▂▇ in your shell"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.0.1
NEOTERM_PKG_SRCURL=$NEOTERM_PKG_HOMEPAGE/archive/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=a81c1bc538ce8e011f62264fe6f33d28042ff431b510a6359040dc77403ebab6
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_DEPENDS=bash
NEOTERM_PKG_PLATFORM_INDEPENDENT=true

neoterm_step_make_install() {
	local bin="$(basename $NEOTERM_PKG_HOMEPAGE)"
	install -D "$bin" -t "$NEOTERM_PREFIX/bin"
}
