NEOTERM_PKG_HOMEPAGE=https://exiv2.org/
NEOTERM_PKG_DESCRIPTION="Exif, Iptc and XMP metadata manipulation library and tools"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=2:0.27.7
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://github.com/Exiv2/exiv2/archive/v${NEOTERM_PKG_VERSION:2}.tar.gz
NEOTERM_PKG_SHA256=551b1266e3aabd321f6d555dccd776128ee449d5039feafee927a1f33f7a9753
NEOTERM_PKG_AUTO_UPDATE=false
NEOTERM_PKG_DEPENDS="libandroid-support, libc++, libexpat, zlib"
NEOTERM_PKG_BREAKS="exiv2-dev"
NEOTERM_PKG_REPLACES="exiv2-dev"

# Do not enable EXIV2_ENABLE_VIDEO, which is affected by CVE-2022-371{8,9}.
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DEXIV2_ENABLE_VIDEO=OFF
-DEXIV2_BUILD_SAMPLES=ON
"
