NEOTERM_PKG_HOMEPAGE=https://www.iodbc.org/
NEOTERM_PKG_DESCRIPTION="Independent Open DataBase Connectivity for Linux, MacOS X and Unix systems"
NEOTERM_PKG_LICENSE="LGPL-2.0, BSD 3-Clause"
NEOTERM_PKG_LICENSE_FILE="LICENSE, LICENSE.BSD, LICENSE.LGPL"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=3.52.16
NEOTERM_PKG_SRCURL=https://github.com/openlink/iODBC/releases/download/v${NEOTERM_PKG_VERSION}/libiodbc-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=3898b32d07961360f6f2cf36db36036b719a230e476469258a80f32243e845fa
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
--disable-libodbc
--with-layout=gnu
"
