NEOTERM_PKG_HOMEPAGE=https://bellard.org/quickjs/
NEOTERM_PKG_DESCRIPTION="QuickJS is a small and embeddable Javascript engine"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
_YEAR=2021
_MONTH=03
_DAY=27
NEOTERM_PKG_VERSION=1:${_YEAR}${_MONTH}${_DAY}
NEOTERM_PKG_REVISION=2
NEOTERM_PKG_SRCURL=https://bellard.org/quickjs/quickjs-${_YEAR}-${_MONTH}-${_DAY}.tar.xz
NEOTERM_PKG_SHA256=a45bface4c3379538dea8533878d694e289330488ea7028b105f72572fe7fe1a
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_NO_STATICSPLIT=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="
CROSS_PREFIX=${NEOTERM_HOST_PLATFORM}-
CONFIG_CLANG=y
CONFIG_DEFAULT_AR=y
-W run-test262
-W run-test262-bn
prefix=$NEOTERM_PREFIX
"
