NEOTERM_PKG_HOMEPAGE=https://github.com/json-c/json-c/wiki
NEOTERM_PKG_DESCRIPTION="A JSON implementation in C"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.17"
NEOTERM_PKG_SRCURL=https://s3.amazonaws.com/json-c_releases/releases/json-c-${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=7550914d58fb63b2c3546f3ccfbe11f1c094147bd31a69dcd23714d7956159e6
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BREAKS="json-c-dev"
NEOTERM_PKG_REPLACES="json-c-dev"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DDISABLE_WERROR=ON
"
