NEOTERM_PKG_HOMEPAGE=https://github.com/venam/2bwm
NEOTERM_PKG_DESCRIPTION="A fast floating WM"
NEOTERM_PKG_LICENSE="ISC"
NEOTERM_PKG_LICENSE_FILE="LICENSE.2bwm, LICENSE.hidden"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.3
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://github.com/venam/2bwm/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=a4889ea4b01b1a3d4a508daa034b9d86676913cbbca1f977858df692a6e2af95
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_DEPENDS="libxcb, xcb-util-keysyms, xcb-util-wm, xcb-util-xrm"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="
PREFIX=$NEOTERM_PREFIX
X11_INCLUDE=$NEOTERM_PREFIX/include
"

neoterm_step_post_get_source() {
	cp $NEOTERM_PKG_BUILDER_DIR/LICENSE.{2bwm,hidden} ./
}
