NEOTERM_PKG_HOMEPAGE="https://github.com/tareksander/neoterm-gui-bash"
NEOTERM_PKG_DESCRIPTION="A bash library for NeoTerm:GUI"
NEOTERM_PKG_LICENSE="MPL-2.0"
NEOTERM_PKG_MAINTAINER="@tareksander"
NEOTERM_PKG_VERSION="0.1.2"
NEOTERM_PKG_SRCURL=https://github.com/tareksander/neoterm-gui-bash/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=e915af020b8c32b9f26ccdff839befb1d8eb7cc231363c6d96868606b71dc8b2
NEOTERM_PKG_HAS_DEBUG=false
NEOTERM_PKG_DEPENDS="jq"
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
