NEOTERM_PKG_HOMEPAGE=https://github.com/facebookincubator/fastmod
NEOTERM_PKG_DESCRIPTION="Regex-based code refactoring utility"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.4.4"
NEOTERM_PKG_SRCURL=https://github.com/facebookincubator/fastmod/archive/v$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=b438cc7564ef34d01f27cdd3cd50ee66a9915b9c50939ca021c6bee2e9c1f069
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
