NEOTERM_PKG_HOMEPAGE=https://github.com/jamie/ciso
NEOTERM_PKG_DESCRIPTION="PSP ISO compression tool"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.0.2
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://github.com/jamie/ciso/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=77a9bb615ca8918ef81f21328cb4fdc58f4cdd854cb11c16bb50a7d4d1625c09
NEOTERM_PKG_DEPENDS="zlib"
NEOTERM_PKG_BUILD_IN_SRC=true

neoterm_step_make_install() {
	install -Dm700 ./"${NEOTERM_PKG_NAME}" "${NEOTERM_PREFIX}"/bin
}
