NEOTERM_PKG_HOMEPAGE=https://github.com/Ro5bert/avra
NEOTERM_PKG_DESCRIPTION="Assember for the Atmel AVR microcontroller family"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.4.2
NEOTERM_PKG_SRCURL=https://github.com/Ro5bert/avra/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=cc56837be973d1a102dc6936a0b7235a1d716c0f7cd053bf77e0620577cff986
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_BUILD_IN_SRC=true
NEOTERM_PKG_EXTRA_MAKE_ARGS="PREFIX=$NEOTERM_PREFIX"
