NEOTERM_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="X.org Bitmap files"
# License: HPND
NEOTERM_PKG_LICENSE="custom"
NEOTERM_PKG_LICENSE_FILE="COPYING"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.1.3
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/data/xbitmaps-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=ad6cad54887832a17d86c2ccfc5e52a1dfab090f8307b152c78b0e1529cd0f7a
NEOTERM_PKG_PLATFORM_INDEPENDENT=true
NEOTERM_PKG_NO_DEVELSPLIT=true
