NEOTERM_PKG_HOMEPAGE=https://gstreamer.freedesktop.org/modules/gst-libav.html
NEOTERM_PKG_DESCRIPTION="GStreamer Libav plug-in contains one plugin with a set of elements using the Libav library code"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.24.0"
NEOTERM_PKG_SRCURL=https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=ab775d5b9a7c84176b29822b68c7a34731280039a20b7db5eb639eddd1466178
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="ffmpeg, glib, gst-plugins-base, gstreamer"
