NEOTERM_PKG_HOMEPAGE=https://www.netfilter.org/projects/libnftnl/
NEOTERM_PKG_DESCRIPTION="Netfilter library providing interface to the nf_tables subsystem"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.2.6"
NEOTERM_PKG_SRCURL=https://netfilter.org/projects/libnftnl/files/libnftnl-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=ceeaea2cd92147da19f13a35a7f1a4bc2767ff897e838e4b479cf54b59c777f4
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libmnl"
NEOTERM_PKG_BREAKS="libnftnl-dev"
NEOTERM_PKG_REPLACES="libnftnl-dev"
