NEOTERM_PKG_HOMEPAGE=https://stachenov.github.io/quazip/
NEOTERM_PKG_DESCRIPTION="Qt/C++ wrapper over minizip library"
NEOTERM_PKG_LICENSE="LGPL-2.1"
NEOTERM_PKG_LICENSE_FILE="COPYING"
NEOTERM_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
NEOTERM_PKG_VERSION=1.4
NEOTERM_PKG_SRCURL=https://github.com/stachenov/quazip/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=79633fd3a18e2d11a7d5c40c4c79c1786ba0c74b59ad752e8429746fe1781dd6
NEOTERM_PKG_DEPENDS="libbz2, libc++, qt5-qtbase, zlib"
NEOTERM_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools"
