NEOTERM_SUBPKG_INCLUDE="lib/mono/"
NEOTERM_SUBPKG_DESCRIPTION="Platform-independent libraries for mono"
NEOTERM_SUBPKG_PLATFORM_INDEPENDENT=true
NEOTERM_SUBPKG_BREAKS="mono (<< 6.12.0.122-2)"
NEOTERM_SUBPKG_REPLACES="mono (<< 6.12.0.122-2)"
