NEOTERM_PKG_HOMEPAGE=https://h3geo.org/
NEOTERM_PKG_DESCRIPTION="A hexagonal hierarchical geospatial indexing system"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.1.0
NEOTERM_PKG_SRCURL=https://github.com/uber/h3/archive/refs/tags/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=ec99f1f5974846bde64f4513cf8d2ea1b8d172d2218ab41803bf6a63532272bc
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"

neoterm_step_pre_configure() {
	LDFLAGS+=" -lm"
}
