NEOTERM_PKG_HOMEPAGE=https://git.vuxu.org/lr/about/
NEOTERM_PKG_DESCRIPTION="list files, recursively, includes the best features of ls, find, stat and du"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.6"
NEOTERM_PKG_SRCURL=https://git.vuxu.org/lr/snapshot/lr-$NEOTERM_PKG_VERSION.tar.xz
NEOTERM_PKG_SHA256=8d98a75cdff289e86b4e40bc7c750cc9b40a1f3d229214937fe601e087a2f61c
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_BUILD_IN_SRC=true
