NEOTERM_PKG_HOMEPAGE=https://docs.xfce.org/apps/xfce4-dict/start
NEOTERM_PKG_DESCRIPTION="Dictionary for XFCE desktop"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="0.8.6"
NEOTERM_PKG_SRCURL=https://archive.xfce.org/src/apps/xfce4-dict/${NEOTERM_PKG_VERSION%.*}/xfce4-dict-${NEOTERM_PKG_VERSION}.tar.bz2
NEOTERM_PKG_SHA256=ae5db7ca70354d3293fc08eaf7ca40cdbc91799a219f199d824684b39e6c0a41
NEOTERM_PKG_DEPENDS="atk, gdk-pixbuf, glib, gtk3, harfbuzz, libcairo, libx11, libxfce4ui, libxfce4util, pango, xfce4-panel, zlib"
NEOTERM_PKG_SUGGESTS="aspell"
NEOTERM_PKG_BUILD_IN_SRC=true
