NEOTERM_PKG_HOMEPAGE=https://github.com/fornwall/vtutils
NEOTERM_PKG_DESCRIPTION="Utilities for testing and working with virtual terminals"
NEOTERM_PKG_LICENSE="Apache-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=0.5
NEOTERM_PKG_REVISION=4
NEOTERM_PKG_SRCURL=https://github.com/fornwall/vtutils/releases/download/v$NEOTERM_PKG_VERSION/vtutils-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=ef0b11f9570697f53bcda7a61093f8d472afee2c8551b5b35e9b5b7c1539c2c6
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libc++"
