NEOTERM_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NEOTERM_PKG_DESCRIPTION="X11 pixmap library"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="3.5.17"
NEOTERM_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXpm-${NEOTERM_PKG_VERSION}.tar.xz
NEOTERM_PKG_SHA256=64b31f81019e7d388c822b0b28af8d51c4622b83f1f0cb6fa3fc95e271226e43
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_DEPENDS="libx11, libxext, libxt"
NEOTERM_PKG_BUILD_DEPENDS="xorg-util-macros"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
ac_cv_path_XPM_PATH_COMPRESS=$NEOTERM_PREFIX/bin/compress
ac_cv_path_XPM_PATH_UNCOMPRESS=$NEOTERM_PREFIX/bin/uncompress
ac_cv_path_XPM_PATH_GZIP=$NEOTERM_PREFIX/bin/gzip
"
