NEOTERM_PKG_HOMEPAGE=https://github.com/zeux/volk
NEOTERM_PKG_DESCRIPTION="Meta loader for Vulkan API"
NEOTERM_PKG_LICENSE="MIT"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION="1.3.270"
NEOTERM_PKG_SRCURL=https://github.com/zeux/volk/archive/refs/tags/${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=95530bc7850b0358e4bad899eb653f882ee8a08088257d90c5042cec02208f52
NEOTERM_PKG_BUILD_DEPENDS="vulkan-headers, vulkan-loader-generic"
NEOTERM_PKG_NO_STATICSPLIT=true
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="
-DVOLK_INSTALL=ON
"
