NEOTERM_PKG_HOMEPAGE=http://software.schmorp.de/pkg/libev.html
NEOTERM_PKG_DESCRIPTION="Full-featured and high-performance event loop library"
NEOTERM_PKG_LICENSE="BSD 2-Clause"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=4.33
NEOTERM_PKG_REVISION=1
NEOTERM_PKG_SRCURL=https://fossies.org/linux/misc/libev-$NEOTERM_PKG_VERSION.tar.gz
NEOTERM_PKG_SHA256=507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
NEOTERM_PKG_BREAKS="libev-dev"
NEOTERM_PKG_REPLACES="libev-dev"
