NEOTERM_PKG_HOMEPAGE=https://github.com/georgmartius/vid.stab
NEOTERM_PKG_DESCRIPTION="video stabilization library"
NEOTERM_PKG_LICENSE="GPL-2.0"
NEOTERM_PKG_MAINTAINER="@neoterm"
NEOTERM_PKG_VERSION=1.1.1
NEOTERM_PKG_SRCURL=https://github.com/georgmartius/vid.stab/archive/v${NEOTERM_PKG_VERSION}.tar.gz
NEOTERM_PKG_SHA256=9001b6df73933555e56deac19a0f225aae152abbc0e97dc70034814a1943f3d4
NEOTERM_PKG_AUTO_UPDATE=true
NEOTERM_PKG_UPDATE_TAG_TYPE="newest-tag"
NEOTERM_PKG_EXTRA_CONFIGURE_ARGS="-DSSE2_FOUND=OFF"
